/** World countries with independence/formation dates for reflective trivia. */
export type TriviaCountry = {
  name: string;
  iso2: string;
  dob: string;
  foundingNote: string;
  lat: number;
  lng: number;
  lifePath: number;
  destiny: number;
  psychic: number;
};

export const TRIVIA_COUNTRIES: TriviaCountry[] = [
  {
    "name": "Afghanistan",
    "iso2": "af",
    "dob": "19/08/1919",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 33,
    "lng": 65,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 1
  },
  {
    "name": "Albania",
    "iso2": "al",
    "dob": "28/11/1912",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 41,
    "lng": 20,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 1
  },
  {
    "name": "Algeria",
    "iso2": "dz",
    "dob": "05/07/1962",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 28,
    "lng": 3,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 5
  },
  {
    "name": "Andorra",
    "iso2": "ad",
    "dob": "08/09/1278",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 42.5,
    "lng": 1.5,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 8
  },
  {
    "name": "Angola",
    "iso2": "ao",
    "dob": "11/11/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -12.5,
    "lng": 18.5,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 2
  },
  {
    "name": "Antigua and Barbuda",
    "iso2": "ag",
    "dob": "01/11/1981",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 17.05,
    "lng": -61.8,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 1
  },
  {
    "name": "Argentina",
    "iso2": "ar",
    "dob": "09/07/1816",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -34,
    "lng": -64,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 9
  },
  {
    "name": "Armenia",
    "iso2": "am",
    "dob": "21/09/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 40,
    "lng": 45,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 3
  },
  {
    "name": "Australia",
    "iso2": "au",
    "dob": "01/01/1901",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -27,
    "lng": 133,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 1
  },
  {
    "name": "Austria",
    "iso2": "at",
    "dob": "26/10/1955",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 47.3,
    "lng": 13.3,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 8
  },
  {
    "name": "Azerbaijan",
    "iso2": "az",
    "dob": "18/10/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 40.5,
    "lng": 47.5,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 9
  },
  {
    "name": "Bahamas",
    "iso2": "bs",
    "dob": "10/07/1973",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 24.25,
    "lng": -76,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 1
  },
  {
    "name": "Bahrain",
    "iso2": "bh",
    "dob": "15/08/1971",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 26,
    "lng": 50.5,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 6
  },
  {
    "name": "Bangladesh",
    "iso2": "bd",
    "dob": "26/03/1971",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 24,
    "lng": 90,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 8
  },
  {
    "name": "Barbados",
    "iso2": "bb",
    "dob": "30/11/1966",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13.2,
    "lng": -59.5,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 3
  },
  {
    "name": "Belarus",
    "iso2": "by",
    "dob": "25/08/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 53,
    "lng": 28,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 7
  },
  {
    "name": "Belgium",
    "iso2": "be",
    "dob": "04/10/1830",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 50.8,
    "lng": 4.5,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 4
  },
  {
    "name": "Belize",
    "iso2": "bz",
    "dob": "21/09/1981",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 17.25,
    "lng": -88.75,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 3
  },
  {
    "name": "Benin",
    "iso2": "bj",
    "dob": "01/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 9.5,
    "lng": 2.25,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 1
  },
  {
    "name": "Bhutan",
    "iso2": "bt",
    "dob": "17/12/1907",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 27.5,
    "lng": 90.5,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 8
  },
  {
    "name": "Bolivia",
    "iso2": "bo",
    "dob": "06/08/1825",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -17,
    "lng": -65,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 6
  },
  {
    "name": "Bosnia and Herzegovina",
    "iso2": "ba",
    "dob": "01/03/1992",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 44,
    "lng": 18,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 1
  },
  {
    "name": "Botswana",
    "iso2": "bw",
    "dob": "30/09/1966",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -22,
    "lng": 24,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 3
  },
  {
    "name": "Brazil",
    "iso2": "br",
    "dob": "07/09/1822",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -10,
    "lng": -55,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 7
  },
  {
    "name": "Brunei",
    "iso2": "bn",
    "dob": "01/01/1984",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 4.5,
    "lng": 114.7,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 1
  },
  {
    "name": "Bulgaria",
    "iso2": "bg",
    "dob": "03/03/1878",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 43,
    "lng": 25,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 3
  },
  {
    "name": "Burkina Faso",
    "iso2": "bf",
    "dob": "05/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13,
    "lng": -2,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 5
  },
  {
    "name": "Burundi",
    "iso2": "bi",
    "dob": "01/07/1962",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -3.5,
    "lng": 30,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 1
  },
  {
    "name": "Cabo Verde",
    "iso2": "cv",
    "dob": "05/07/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 16,
    "lng": -24,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 5
  },
  {
    "name": "Cambodia",
    "iso2": "kh",
    "dob": "09/11/1953",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13,
    "lng": 105,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 9
  },
  {
    "name": "Cameroon",
    "iso2": "cm",
    "dob": "01/01/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 6,
    "lng": 12,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 1
  },
  {
    "name": "Canada",
    "iso2": "ca",
    "dob": "01/07/1867",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 60,
    "lng": -95,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 1
  },
  {
    "name": "Central African Republic",
    "iso2": "cf",
    "dob": "13/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 7,
    "lng": 21,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 4
  },
  {
    "name": "Chad",
    "iso2": "td",
    "dob": "11/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15,
    "lng": 19,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 2
  },
  {
    "name": "Chile",
    "iso2": "cl",
    "dob": "18/09/1810",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -30,
    "lng": -71,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 9
  },
  {
    "name": "China",
    "iso2": "cn",
    "dob": "01/10/1949",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 35,
    "lng": 105,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 1
  },
  {
    "name": "Colombia",
    "iso2": "co",
    "dob": "20/07/1810",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 4,
    "lng": -72,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 2
  },
  {
    "name": "Comoros",
    "iso2": "km",
    "dob": "06/07/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -12.2,
    "lng": 44.3,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 6
  },
  {
    "name": "Congo",
    "iso2": "cg",
    "dob": "15/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -1,
    "lng": 15,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 6
  },
  {
    "name": "Costa Rica",
    "iso2": "cr",
    "dob": "15/09/1821",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 10,
    "lng": -84,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "Croatia",
    "iso2": "hr",
    "dob": "25/06/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 45.2,
    "lng": 15.5,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 7
  },
  {
    "name": "Cuba",
    "iso2": "cu",
    "dob": "20/05/1902",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 22,
    "lng": -80,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 2
  },
  {
    "name": "Cyprus",
    "iso2": "cy",
    "dob": "16/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 35,
    "lng": 33,
    "lifePath": 22,
    "destiny": 4,
    "psychic": 7
  },
  {
    "name": "Czechia",
    "iso2": "cz",
    "dob": "01/01/1993",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 49.75,
    "lng": 15.5,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 1
  },
  {
    "name": "Denmark",
    "iso2": "dk",
    "dob": "05/06/1849",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 56,
    "lng": 10,
    "lifePath": 33,
    "destiny": 6,
    "psychic": 5
  },
  {
    "name": "Djibouti",
    "iso2": "dj",
    "dob": "27/06/1977",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 11.5,
    "lng": 43,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 9
  },
  {
    "name": "Dominica",
    "iso2": "dm",
    "dob": "03/11/1978",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15.4,
    "lng": -61.3,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 3
  },
  {
    "name": "Dominican Republic",
    "iso2": "do",
    "dob": "27/02/1844",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 19,
    "lng": -70.7,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 9
  },
  {
    "name": "Ecuador",
    "iso2": "ec",
    "dob": "10/08/1809",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -2,
    "lng": -77.5,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 1
  },
  {
    "name": "Egypt",
    "iso2": "eg",
    "dob": "28/02/1922",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 27,
    "lng": 30,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 1
  },
  {
    "name": "El Salvador",
    "iso2": "sv",
    "dob": "15/09/1821",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13.8,
    "lng": -88.9,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "Equatorial Guinea",
    "iso2": "gq",
    "dob": "12/10/1968",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 2,
    "lng": 10,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 3
  },
  {
    "name": "Eritrea",
    "iso2": "er",
    "dob": "24/05/1993",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15,
    "lng": 39,
    "lifePath": 33,
    "destiny": 6,
    "psychic": 6
  },
  {
    "name": "Estonia",
    "iso2": "ee",
    "dob": "24/02/1918",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 59,
    "lng": 26,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "Eswatini",
    "iso2": "sz",
    "dob": "06/09/1968",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -26.5,
    "lng": 31.5,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 6
  },
  {
    "name": "Ethiopia",
    "iso2": "et",
    "dob": "28/05/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 8,
    "lng": 38,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 1
  },
  {
    "name": "Fiji",
    "iso2": "fj",
    "dob": "10/10/1970",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -18,
    "lng": 175,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 1
  },
  {
    "name": "Finland",
    "iso2": "fi",
    "dob": "06/12/1917",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 64,
    "lng": 26,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "France",
    "iso2": "fr",
    "dob": "14/07/1789",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 46,
    "lng": 2,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 5
  },
  {
    "name": "Gabon",
    "iso2": "ga",
    "dob": "17/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -1,
    "lng": 11.7,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 8
  },
  {
    "name": "Gambia",
    "iso2": "gm",
    "dob": "18/02/1965",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13.5,
    "lng": -15.5,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 9
  },
  {
    "name": "Georgia",
    "iso2": "ge",
    "dob": "09/04/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 42,
    "lng": 43.5,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 9
  },
  {
    "name": "Germany",
    "iso2": "de",
    "dob": "03/10/1990",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 51,
    "lng": 9,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 3
  },
  {
    "name": "Ghana",
    "iso2": "gh",
    "dob": "06/03/1957",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 8,
    "lng": -2,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 6
  },
  {
    "name": "Greece",
    "iso2": "gr",
    "dob": "25/03/1821",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 39,
    "lng": 22,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 7
  },
  {
    "name": "Grenada",
    "iso2": "gd",
    "dob": "07/02/1974",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 12.1,
    "lng": -61.7,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 7
  },
  {
    "name": "Guatemala",
    "iso2": "gt",
    "dob": "15/09/1821",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15.5,
    "lng": -90.2,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "Guinea",
    "iso2": "gn",
    "dob": "02/10/1958",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 11,
    "lng": -10,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 2
  },
  {
    "name": "Guinea-Bissau",
    "iso2": "gw",
    "dob": "24/09/1973",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 12,
    "lng": -15,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 6
  },
  {
    "name": "Guyana",
    "iso2": "gy",
    "dob": "26/05/1966",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 5,
    "lng": -59,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 8
  },
  {
    "name": "Haiti",
    "iso2": "ht",
    "dob": "01/01/1804",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 19,
    "lng": -72.4,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 1
  },
  {
    "name": "Honduras",
    "iso2": "hn",
    "dob": "15/09/1821",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15,
    "lng": -86.5,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "Hungary",
    "iso2": "hu",
    "dob": "16/11/1918",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 47,
    "lng": 20,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 7
  },
  {
    "name": "Iceland",
    "iso2": "is",
    "dob": "17/06/1944",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 65,
    "lng": -18,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 8
  },
  {
    "name": "India",
    "iso2": "in",
    "dob": "15/08/1947",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 20,
    "lng": 77,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 6
  },
  {
    "name": "Indonesia",
    "iso2": "id",
    "dob": "17/08/1945",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -5,
    "lng": 120,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 8
  },
  {
    "name": "Iran",
    "iso2": "ir",
    "dob": "01/04/1979",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 32,
    "lng": 53,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 1
  },
  {
    "name": "Iraq",
    "iso2": "iq",
    "dob": "03/10/1932",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 33,
    "lng": 44,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 3
  },
  {
    "name": "Ireland",
    "iso2": "ie",
    "dob": "06/12/1922",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 53,
    "lng": -8,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 6
  },
  {
    "name": "Israel",
    "iso2": "il",
    "dob": "14/05/1948",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 31.5,
    "lng": 34.8,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 5
  },
  {
    "name": "Italy",
    "iso2": "it",
    "dob": "17/03/1861",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 42.8,
    "lng": 12.8,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 8
  },
  {
    "name": "Jamaica",
    "iso2": "jm",
    "dob": "06/08/1962",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 18.25,
    "lng": -77.5,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 6
  },
  {
    "name": "Japan",
    "iso2": "jp",
    "dob": "11/02/1952",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 36,
    "lng": 138,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 2
  },
  {
    "name": "Jordan",
    "iso2": "jo",
    "dob": "25/05/1946",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 31,
    "lng": 36,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 7
  },
  {
    "name": "Kazakhstan",
    "iso2": "kz",
    "dob": "16/12/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 48,
    "lng": 68,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 7
  },
  {
    "name": "Kenya",
    "iso2": "ke",
    "dob": "12/12/1963",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 1,
    "lng": 38,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 3
  },
  {
    "name": "Kiribati",
    "iso2": "ki",
    "dob": "12/07/1979",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 1.4,
    "lng": 173,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 3
  },
  {
    "name": "Kuwait",
    "iso2": "kw",
    "dob": "19/06/1961",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 29.5,
    "lng": 47.8,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 1
  },
  {
    "name": "Kyrgyzstan",
    "iso2": "kg",
    "dob": "31/08/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 41,
    "lng": 83,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 4
  },
  {
    "name": "Laos",
    "iso2": "la",
    "dob": "22/10/1953",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 18,
    "lng": 105,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 4
  },
  {
    "name": "Latvia",
    "iso2": "lv",
    "dob": "18/11/1918",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 57,
    "lng": 25,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 9
  },
  {
    "name": "Lebanon",
    "iso2": "lb",
    "dob": "22/11/1943",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 33.8,
    "lng": 35.8,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 4
  },
  {
    "name": "Lesotho",
    "iso2": "ls",
    "dob": "04/10/1966",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -29.5,
    "lng": 28.5,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 4
  },
  {
    "name": "Liberia",
    "iso2": "lr",
    "dob": "26/07/1847",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 6.5,
    "lng": -9.5,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 8
  },
  {
    "name": "Libya",
    "iso2": "ly",
    "dob": "24/12/1951",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 25,
    "lng": 17,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 6
  },
  {
    "name": "Liechtenstein",
    "iso2": "li",
    "dob": "23/01/1719",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 47.15,
    "lng": 9.55,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 5
  },
  {
    "name": "Lithuania",
    "iso2": "lt",
    "dob": "16/02/1918",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 56,
    "lng": 24,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 7
  },
  {
    "name": "Luxembourg",
    "iso2": "lu",
    "dob": "23/01/1839",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 49.75,
    "lng": 6.15,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 5
  },
  {
    "name": "Madagascar",
    "iso2": "mg",
    "dob": "26/06/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -20,
    "lng": 47,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 8
  },
  {
    "name": "Malawi",
    "iso2": "mw",
    "dob": "06/07/1964",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -13.5,
    "lng": 34,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 6
  },
  {
    "name": "Malaysia",
    "iso2": "my",
    "dob": "31/08/1957",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 2.5,
    "lng": 112.5,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 4
  },
  {
    "name": "Maldives",
    "iso2": "mv",
    "dob": "26/07/1965",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 3.25,
    "lng": 73,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 8
  },
  {
    "name": "Mali",
    "iso2": "ml",
    "dob": "22/09/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 17,
    "lng": -4,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 4
  },
  {
    "name": "Malta",
    "iso2": "mt",
    "dob": "21/09/1964",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 35.9,
    "lng": 14.5,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 3
  },
  {
    "name": "Marshall Islands",
    "iso2": "mh",
    "dob": "21/10/1986",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 9,
    "lng": 168,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 3
  },
  {
    "name": "Mauritania",
    "iso2": "mr",
    "dob": "28/11/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 20,
    "lng": -12,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 1
  },
  {
    "name": "Mauritius",
    "iso2": "mu",
    "dob": "12/03/1968",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -20.3,
    "lng": 57.5,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 3
  },
  {
    "name": "Mexico",
    "iso2": "mx",
    "dob": "16/09/1810",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 23,
    "lng": -102,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 7
  },
  {
    "name": "Micronesia",
    "iso2": "fm",
    "dob": "03/11/1986",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 6.9,
    "lng": 158.2,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 3
  },
  {
    "name": "Moldova",
    "iso2": "md",
    "dob": "27/08/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 47,
    "lng": 29,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 9
  },
  {
    "name": "Monaco",
    "iso2": "mc",
    "dob": "08/01/1297",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 43.7,
    "lng": 7.4,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 8
  },
  {
    "name": "Mongolia",
    "iso2": "mn",
    "dob": "29/12/1911",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 46,
    "lng": 105,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 2
  },
  {
    "name": "Montenegro",
    "iso2": "me",
    "dob": "03/06/2006",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 42.5,
    "lng": 19.3,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 3
  },
  {
    "name": "Morocco",
    "iso2": "ma",
    "dob": "02/03/1956",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 32,
    "lng": -5,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 2
  },
  {
    "name": "Mozambique",
    "iso2": "mz",
    "dob": "25/06/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -18.25,
    "lng": 35,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 7
  },
  {
    "name": "Myanmar",
    "iso2": "mm",
    "dob": "04/01/1948",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 22,
    "lng": 98,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 4
  },
  {
    "name": "Namibia",
    "iso2": "na",
    "dob": "21/03/1990",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -22,
    "lng": 17,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 3
  },
  {
    "name": "Nauru",
    "iso2": "nr",
    "dob": "31/01/1968",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -0.5,
    "lng": 166.9,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 4
  },
  {
    "name": "Nepal",
    "iso2": "np",
    "dob": "28/05/2008",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 28,
    "lng": 84,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 1
  },
  {
    "name": "Netherlands",
    "iso2": "nl",
    "dob": "26/07/1581",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 52.5,
    "lng": 5.75,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 8
  },
  {
    "name": "New Zealand",
    "iso2": "nz",
    "dob": "06/02/1840",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -41,
    "lng": 174,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 6
  },
  {
    "name": "Nicaragua",
    "iso2": "ni",
    "dob": "15/09/1821",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13,
    "lng": -85,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "Niger",
    "iso2": "ne",
    "dob": "03/08/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 16,
    "lng": 8,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 3
  },
  {
    "name": "Nigeria",
    "iso2": "ng",
    "dob": "01/10/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 10,
    "lng": 8,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 1
  },
  {
    "name": "North Korea",
    "iso2": "kp",
    "dob": "09/09/1948",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 40,
    "lng": 127,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 9
  },
  {
    "name": "North Macedonia",
    "iso2": "mk",
    "dob": "08/09/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 41.8,
    "lng": 22,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 8
  },
  {
    "name": "Norway",
    "iso2": "no",
    "dob": "17/05/1814",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 62,
    "lng": 10,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 8
  },
  {
    "name": "Oman",
    "iso2": "om",
    "dob": "18/11/1650",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 21,
    "lng": 57,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 9
  },
  {
    "name": "Pakistan",
    "iso2": "pk",
    "dob": "14/08/1947",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 30,
    "lng": 70,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 5
  },
  {
    "name": "Palau",
    "iso2": "pw",
    "dob": "01/10/1994",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 7.5,
    "lng": 134.5,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 1
  },
  {
    "name": "Panama",
    "iso2": "pa",
    "dob": "03/11/1903",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 9,
    "lng": -80,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 3
  },
  {
    "name": "Papua New Guinea",
    "iso2": "pg",
    "dob": "16/09/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -6,
    "lng": 147,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 7
  },
  {
    "name": "Paraguay",
    "iso2": "py",
    "dob": "14/05/1811",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -23,
    "lng": -58,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 5
  },
  {
    "name": "Peru",
    "iso2": "pe",
    "dob": "28/07/1821",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -10,
    "lng": -76,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 1
  },
  {
    "name": "Philippines",
    "iso2": "ph",
    "dob": "12/06/1898",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13,
    "lng": 122,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 3
  },
  {
    "name": "Poland",
    "iso2": "pl",
    "dob": "11/11/1918",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 52,
    "lng": 20,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 2
  },
  {
    "name": "Portugal",
    "iso2": "pt",
    "dob": "05/10/1910",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 39.5,
    "lng": -8,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 5
  },
  {
    "name": "Qatar",
    "iso2": "qa",
    "dob": "03/09/1971",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 25.5,
    "lng": 51.25,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 3
  },
  {
    "name": "Romania",
    "iso2": "ro",
    "dob": "09/05/1877",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 46,
    "lng": 25,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 9
  },
  {
    "name": "Russia",
    "iso2": "ru",
    "dob": "12/06/1990",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 60,
    "lng": 100,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 3
  },
  {
    "name": "Rwanda",
    "iso2": "rw",
    "dob": "01/07/1962",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -2,
    "lng": 30,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 1
  },
  {
    "name": "Saint Kitts and Nevis",
    "iso2": "kn",
    "dob": "19/09/1983",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 17.3,
    "lng": -62.7,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 1
  },
  {
    "name": "Saint Lucia",
    "iso2": "lc",
    "dob": "22/02/1979",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13.9,
    "lng": -61,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 4
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "iso2": "vc",
    "dob": "27/10/1979",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 13.25,
    "lng": -61.2,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 9
  },
  {
    "name": "Samoa",
    "iso2": "ws",
    "dob": "01/01/1962",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -13.6,
    "lng": -172.3,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 1
  },
  {
    "name": "San Marino",
    "iso2": "sm",
    "dob": "03/09/1600",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 43.9,
    "lng": 12.45,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 3
  },
  {
    "name": "Sao Tome and Principe",
    "iso2": "st",
    "dob": "12/07/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 1,
    "lng": 7,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 3
  },
  {
    "name": "Saudi Arabia",
    "iso2": "sa",
    "dob": "23/09/1932",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 25,
    "lng": 45,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 5
  },
  {
    "name": "Senegal",
    "iso2": "sn",
    "dob": "04/04/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 14,
    "lng": -14,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 4
  },
  {
    "name": "Serbia",
    "iso2": "rs",
    "dob": "05/06/2006",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 44,
    "lng": 21,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 5
  },
  {
    "name": "Seychelles",
    "iso2": "sc",
    "dob": "29/06/1976",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -4.6,
    "lng": 55.5,
    "lifePath": 22,
    "destiny": 4,
    "psychic": 2
  },
  {
    "name": "Sierra Leone",
    "iso2": "sl",
    "dob": "27/04/1961",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 8.5,
    "lng": -11.5,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 9
  },
  {
    "name": "Singapore",
    "iso2": "sg",
    "dob": "09/08/1965",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 1.3,
    "lng": 103.8,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 9
  },
  {
    "name": "Slovakia",
    "iso2": "sk",
    "dob": "01/01/1993",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 48.7,
    "lng": 19.5,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 1
  },
  {
    "name": "Slovenia",
    "iso2": "si",
    "dob": "25/06/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 46.1,
    "lng": 14.8,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 7
  },
  {
    "name": "Solomon Islands",
    "iso2": "sb",
    "dob": "07/07/1978",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -8,
    "lng": 159,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 7
  },
  {
    "name": "Somalia",
    "iso2": "so",
    "dob": "01/07/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 10,
    "lng": 49,
    "lifePath": 6,
    "destiny": 6,
    "psychic": 1
  },
  {
    "name": "South Africa",
    "iso2": "za",
    "dob": "31/05/1910",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -29,
    "lng": 24,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 4
  },
  {
    "name": "South Korea",
    "iso2": "kr",
    "dob": "15/08/1948",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 37,
    "lng": 127.5,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "South Sudan",
    "iso2": "ss",
    "dob": "09/07/2011",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 7,
    "lng": 30,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 9
  },
  {
    "name": "Spain",
    "iso2": "es",
    "dob": "20/11/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 40,
    "lng": -4,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 2
  },
  {
    "name": "Sri Lanka",
    "iso2": "lk",
    "dob": "04/02/1948",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 7,
    "lng": 81,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 4
  },
  {
    "name": "Sudan",
    "iso2": "sd",
    "dob": "01/01/1956",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15,
    "lng": 30,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 1
  },
  {
    "name": "Suriname",
    "iso2": "sr",
    "dob": "25/11/1975",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 4,
    "lng": -56,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 7
  },
  {
    "name": "Sweden",
    "iso2": "se",
    "dob": "06/06/1523",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 62,
    "lng": 15,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 6
  },
  {
    "name": "Switzerland",
    "iso2": "ch",
    "dob": "01/08/1291",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 47,
    "lng": 8,
    "lifePath": 4,
    "destiny": 4,
    "psychic": 1
  },
  {
    "name": "Syria",
    "iso2": "sy",
    "dob": "17/04/1946",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 35,
    "lng": 38,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 8
  },
  {
    "name": "Tajikistan",
    "iso2": "tj",
    "dob": "09/09/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 39,
    "lng": 71,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 9
  },
  {
    "name": "Tanzania",
    "iso2": "tz",
    "dob": "09/12/1961",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -6,
    "lng": 35,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 9
  },
  {
    "name": "Thailand",
    "iso2": "th",
    "dob": "24/06/1939",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15,
    "lng": 100,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 6
  },
  {
    "name": "Timor-Leste",
    "iso2": "tl",
    "dob": "20/05/2002",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -8.8,
    "lng": 125.7,
    "lifePath": 11,
    "destiny": 2,
    "psychic": 2
  },
  {
    "name": "Togo",
    "iso2": "tg",
    "dob": "27/04/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 8,
    "lng": 1.2,
    "lifePath": 2,
    "destiny": 2,
    "psychic": 9
  },
  {
    "name": "Tonga",
    "iso2": "to",
    "dob": "04/06/1970",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -20,
    "lng": -175,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 4
  },
  {
    "name": "Trinidad and Tobago",
    "iso2": "tt",
    "dob": "31/08/1962",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 11,
    "lng": -61,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 4
  },
  {
    "name": "Tunisia",
    "iso2": "tn",
    "dob": "20/03/1956",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 34,
    "lng": 9,
    "lifePath": 8,
    "destiny": 8,
    "psychic": 2
  },
  {
    "name": "Turkey",
    "iso2": "tr",
    "dob": "29/10/1923",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 39,
    "lng": 35,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 2
  },
  {
    "name": "Turkmenistan",
    "iso2": "tm",
    "dob": "27/10/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 40,
    "lng": 60,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 9
  },
  {
    "name": "Tuvalu",
    "iso2": "tv",
    "dob": "01/10/1978",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -8,
    "lng": 178,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 1
  },
  {
    "name": "Uganda",
    "iso2": "ug",
    "dob": "09/10/1962",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 1,
    "lng": 32,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 9
  },
  {
    "name": "Ukraine",
    "iso2": "ua",
    "dob": "24/08/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 49,
    "lng": 32,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 6
  },
  {
    "name": "United Arab Emirates",
    "iso2": "ae",
    "dob": "02/12/1971",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 24,
    "lng": 54,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 2
  },
  {
    "name": "United Kingdom",
    "iso2": "gb",
    "dob": "01/01/1801",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 54,
    "lng": -2,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 1
  },
  {
    "name": "United States",
    "iso2": "us",
    "dob": "04/07/1776",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 38,
    "lng": -97,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 4
  },
  {
    "name": "Uruguay",
    "iso2": "uy",
    "dob": "25/08/1825",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -33,
    "lng": -56,
    "lifePath": 22,
    "destiny": 4,
    "psychic": 7
  },
  {
    "name": "Uzbekistan",
    "iso2": "uz",
    "dob": "01/09/1991",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 41,
    "lng": 64,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 1
  },
  {
    "name": "Vanuatu",
    "iso2": "vu",
    "dob": "30/07/1980",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -16,
    "lng": 167,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 3
  },
  {
    "name": "Vatican City",
    "iso2": "va",
    "dob": "11/02/1929",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 41.9,
    "lng": 12.45,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 2
  },
  {
    "name": "Venezuela",
    "iso2": "ve",
    "dob": "05/07/1811",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 8,
    "lng": -66,
    "lifePath": 5,
    "destiny": 5,
    "psychic": 5
  },
  {
    "name": "Vietnam",
    "iso2": "vn",
    "dob": "02/09/1945",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 16,
    "lng": 108,
    "lifePath": 3,
    "destiny": 3,
    "psychic": 2
  },
  {
    "name": "Yemen",
    "iso2": "ye",
    "dob": "22/05/1990",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": 15.5,
    "lng": 47.5,
    "lifePath": 1,
    "destiny": 1,
    "psychic": 4
  },
  {
    "name": "Zambia",
    "iso2": "zm",
    "dob": "24/10/1964",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -15,
    "lng": 30,
    "lifePath": 9,
    "destiny": 9,
    "psychic": 6
  },
  {
    "name": "Zimbabwe",
    "iso2": "zw",
    "dob": "18/04/1980",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -20,
    "lng": 30,
    "lifePath": 22,
    "destiny": 4,
    "psychic": 9
  },
  {
    "name": "Democratic Republic of the Congo",
    "iso2": "cd",
    "dob": "30/06/1960",
    "foundingNote": "Independence / formation date used for reflective trivia",
    "lat": -4,
    "lng": 25,
    "lifePath": 7,
    "destiny": 7,
    "psychic": 3
  }
];
