/** Curated famous personalities for reflective trivia (DOB-based match). */
export type TriviaPerson = {
  name: string;
  dob: string;
  note: string;
  lifePath: number;
  destiny: number;
  psychic: number;
};

export const TRIVIA_PEOPLE: TriviaPerson[] = [
  {"name":"Lorenzo de'Medici","dob":"01/01/1449","note":"(The Magnificent) of Florence","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Sir James Frazer","dob":"01/01/1854","note":"British anthropologist and author (The Golden Bough)","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Isaac Asimov","dob":"02/01/1920","note":"Scientist-writer","lifePath":6,"destiny":6,"psychic":2},
  {"name":"James Wolfe","dob":"02/01/1727","note":"Commander of British Army at capture of Quebec","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Henry Handel Richardson","dob":"03/01/1870","note":"Australian novelist (Richard Mahoney)","lifePath":11,"destiny":2,"psychic":3},
  {"name":"Juan Cabrillo","dob":"03/01/1543","note":"Discoverer of California","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Bishop James Ussher","dob":"04/01/1581","note":"Calculated that earth began Nov. 23-4004 BC","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Isaac Newton","dob":"04/01/1643","note":"Physicist","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Jacob Grimm","dob":"04/01/1785","note":"German librarian and philologist and fairy tale collector","lifePath":8,"destiny":8,"psychic":4},
  {"name":"Konrad Adenauer","dob":"05/01/1876","note":"German Chancellor","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Shah Jahan","dob":"05/01/1592","note":"Mughal emperor of India (1628-58) and builder of Taj Mahal","lifePath":5,"destiny":5,"psychic":5},
  {"name":"A. R. Rahman","dob":"06/01/1967","note":"Composer","lifePath":3,"destiny":3,"psychic":6},
  {"name":"Khalil Gibran","dob":"06/01/1883","note":"Lebanese mystic poet (The Prophet and Broken Wings)","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Sun Myung Moon","dob":"06/01/1920","note":"Evangelist (Unification Church)","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Gerald Durrell","dob":"07/01/1925","note":"British zoologist and writer and broadcaster","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Millard Fillmore","dob":"07/01/1800","note":"(Whig) 13th US pres (1850-53)","lifePath":8,"destiny":8,"psychic":7},
  {"name":"David Bowie","dob":"08/01/1947","note":"Singer and Actor","lifePath":3,"destiny":3,"psychic":8},
  {"name":"Elvis Presley","dob":"08/01/1935","note":"Musician","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Stephen Hawking","dob":"08/01/1942","note":"Physicist","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Joan Baez","dob":"09/01/1941","note":"Folk singer and human rights advocate in Staten Island","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Simone de Beauvoir","dob":"09/01/1908","note":"French author (The Mandarins and The Second Sex)","lifePath":1,"destiny":1,"psychic":9},
  {"name":"George Foreman","dob":"10/01/1949","note":"World heavyweight boxing champ (1973-74)","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Manuel Azasa y Diaz","dob":"10/01/1880","note":"P.M. and president of 2nd Spanish republic","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Albert Hofmann","dob":"11/01/1906","note":"Swiss chemist and discoverer of LSD","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Alexander Hamilton","dob":"11/01/1755","note":"1st Sec of US Treasury","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Edmund Burke","dob":"12/01/1729","note":"Famous Whig","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Jack London","dob":"12/01/1876","note":"Writer (Call of the Wild)","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Jeff Bezos","dob":"12/01/1964","note":"Entrepreneur","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Swami Vivekananda","dob":"12/01/1863","note":"Philosopher","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Geoffrey Canada","dob":"13/01/1952","note":"Notable public figure","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Salmon P. Chase (R)","dob":"13/01/1808","note":"Senator and cabinet member and 6th chief justice","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Albert Schweitzer","dob":"14/01/1875","note":"Doctor and humanitarian and organist (Nobel 1952)","lifePath":9,"destiny":9,"psychic":5},
  {"name":"John dos Passos","dob":"14/01/1896","note":"Novelist (1919 and Big Money and 42nd Parallel)","lifePath":3,"destiny":3,"psychic":5},
  {"name":"Aristotle Onassis","dob":"15/01/1906","note":"Industrialist","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Chuck Berry","dob":"15/01/1926","note":"Singer (Johnny B. Goode)","lifePath":7,"destiny":7,"psychic":6},
  {"name":"Martin Luther King Jr.","dob":"15/01/1929","note":"Leader","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Andre Michelin","dob":"16/01/1853","note":"French industrialist and tire manufacturer","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Robert Service","dob":"16/01/1874","note":"Canadian poet (Cremation of Sam McGee)","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Benjamin Franklin","dob":"17/01/1706","note":"Polymath","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Muhammad Ali","dob":"17/01/1942","note":"Athlete","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Stanislaw II","dob":"17/01/1732","note":"Last king of Poland (1764-95)","lifePath":4,"destiny":4,"psychic":8},
  {"name":"Cary Grant","dob":"18/01/1904","note":"Actor (Arsenic & Old Lace and North by Northwest)","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Muhammad Ali","dob":"18/01/1942","note":"(aka Cassius Clay) -- boxer","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Auguste Comte","dob":"19/01/1798","note":"Philosopher and founder of sociology & Positivism","lifePath":9,"destiny":9,"psychic":1},
  {"name":"Janis Joplin","dob":"19/01/1943","note":"In Port Arthur Texas","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Charles III","dob":"20/01/1760","note":"King of Spain (1759-88)","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Federico Fellini","dob":"20/01/1920","note":"Director (8« and Satyricon","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Benny Hill","dob":"21/01/1924","note":"British comedian","lifePath":11,"destiny":2,"psychic":3},
  {"name":"Charles V","dob":"21/01/1338","note":"(The Wise) King of France (1364-80)","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Francis Bacon","dob":"22/01/1561","note":"English statesman and essayist (Novum Organum)","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Gotthold Ephraim Lessing","dob":"22/01/1729","note":"German critic and dramatist","lifePath":6,"destiny":6,"psychic":4},
  {"name":"David Hilbert","dob":"23/01/1862","note":"Mathematician","lifePath":5,"destiny":5,"psychic":5},
  {"name":"Humphrey Bogart","dob":"23/01/1899","note":"Actor","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Gustav III","dob":"24/01/1746","note":"King during Swedish Enlightenment (1771-92)","lifePath":7,"destiny":7,"psychic":6},
  {"name":"John Belushi","dob":"24/01/1949","note":"Commedian and Actor (Sat Night Live and Blues Brothers)","lifePath":3,"destiny":3,"psychic":6},
  {"name":"Robert Boyle","dob":"25/01/1627","note":"Irish physicist and chemist and author","lifePath":6,"destiny":6,"psychic":7},
  {"name":"Virginia Woolf","dob":"25/01/1882","note":"Writer","lifePath":9,"destiny":9,"psychic":7},
  {"name":"Volodymyr Zelenskyy","dob":"25/01/1978","note":"Statesman","lifePath":6,"destiny":6,"psychic":7},
  {"name":"Claude Helvetius","dob":"26/01/1715","note":"French philosopher","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Paul Newman","dob":"26/01/1925","note":"Actor (Hud - Hombre - Hustler) and racer & popcorn mogul","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Dmitri Mendeleev","dob":"27/01/1834","note":"Discoverer of periodic table (or 1919)","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Wolfgang Amadeus Mozart","dob":"27/01/1756","note":"Composer","lifePath":11,"destiny":2,"psychic":9},
  {"name":"Alan Alda","dob":"28/01/1936","note":"Actor (Hawkeye Pierce)","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Mikhail Baryshnikov","dob":"28/01/1948","note":"Ballet dancer","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Oprah Winfrey","dob":"29/01/1954","note":"Media","lifePath":4,"destiny":4,"psychic":2},
  {"name":"Oprah Winfrey","dob":"29/01/1953","note":"Actress and TV host (The Color Purple)","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Thomas Paine","dob":"29/01/1737","note":"Political essayist (Common Sense and Age of Reason)","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Dick Cheney","dob":"30/01/1941","note":"Politician, Government","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Franklin D. Roosevelt","dob":"30/01/1882","note":"Statesman","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Vanessa Redgrave","dob":"30/01/1937","note":"Actress (Blow-Up and Julia and Orient Express) in London","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Franz Schubert","dob":"31/01/1797","note":"Composer (Unfinished Symphony)","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Jackie Robinson","dob":"31/01/1919","note":"1st black major league baseball player","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Auguste Blanqui","dob":"01/02/1805","note":"French revolutionary workers' leader","lifePath":8,"destiny":8,"psychic":1},
  {"name":"Clark Gable","dob":"01/02/1901","note":"Didn't give a damn about Scarlet O'Hara","lifePath":5,"destiny":5,"psychic":1},
  {"name":"James Joyce","dob":"02/02/1882","note":"Irish novelist & poet (Dubliners & Ulysses)","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Jascha Heifetz","dob":"02/02/1901","note":"Violin virtuoso","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Norman Rockwell","dob":"03/02/1894","note":"Artist (Saturday Evening Post covers)","lifePath":9,"destiny":9,"psychic":3},
  {"name":"Robert Cecil","dob":"03/02/1830","note":"Marquess of Salisbury (C) & British P.M. (1885-1902)","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Alice Cooper","dob":"04/02/1948","note":"Singer","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Ludwig Prandtl","dob":"04/02/1875","note":"German physicist & father of aerodynamics","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Rosa Parks","dob":"04/02/1913","note":"Activist","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Charlotte Rampling","dob":"05/02/1946","note":"In England","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Cristiano Ronaldo","dob":"05/02/1985","note":"Athlete","lifePath":3,"destiny":3,"psychic":5},
  {"name":"Hank Aaron","dob":"05/02/1934","note":"Baseball player (record 755 HR's)","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Bob Marley","dob":"06/02/1945","note":"Reggae musician","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Ronald Reagan","dob":"06/02/1911","note":"(R) Actor & 40th US pres (1981-89)","lifePath":11,"destiny":2,"psychic":6},
  {"name":"Alfred Adler","dob":"07/02/1870","note":"Austrian psychiatrist","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Charles Dickens","dob":"07/02/1812","note":"Writer","lifePath":3,"destiny":3,"psychic":7},
  {"name":"Jules Verne","dob":"08/02/1828","note":"In France--pioneered sci-fi (From the Earth to the Moon)","lifePath":11,"destiny":2,"psychic":8},
  {"name":"Lana Turner","dob":"08/02/1920","note":"Actress in Wallace Idaho","lifePath":4,"destiny":4,"psychic":8},
  {"name":"Brendan Behan","dob":"09/02/1923","note":"Irish author (The Hostage)","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Mia Farrow","dob":"09/02/1945","note":"Actress (Rosemary's Baby) LA","lifePath":3,"destiny":3,"psychic":9},
  {"name":"Bertolt Brecht","dob":"10/02/1898","note":"German playwright (Mother Courage)","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Boris Pasternak","dob":"10/02/1890","note":"Russian novelist & poet (Dr. Zhivago) (Nobel 1958)","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Burt Reynolds","dob":"11/02/1936","note":"Actor (Deliverance & The End & Smokey & the Bandit)","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Leo Szilard","dob":"11/02/1898","note":"Hungarian physicist & A-bomb worker & peace activist","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Thomas Edison","dob":"11/02/1847","note":"Inventor","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Abraham Lincoln","dob":"12/02/1809","note":"Statesman","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Charles Darwin","dob":"12/02/1809","note":"Evolutionist--Shrewsbury, England","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Georges Simenon","dob":"13/02/1903","note":"Belgian mystery writer (The Snow Was Black)","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Talleyrand","dob":"13/02/1764","note":"In France--statesman","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Edmund George Love","dob":"14/02/1912","note":"American teacher & historian & author","lifePath":11,"destiny":2,"psychic":5},
  {"name":"Frederick Douglass","dob":"14/02/1818","note":"Orator","lifePath":7,"destiny":7,"psychic":5},
  {"name":"Thomas Malthus","dob":"14/02/1766","note":"Population expert","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Galileo Galilei","dob":"15/02/1564","note":"Astronomer","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Jeremy Bentham","dob":"15/02/1748","note":"Utilitarian philosopher & economist","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Henry Wilson","dob":"16/02/1812","note":"(R), 18th VP (1873-75)","lifePath":3,"destiny":3,"psychic":7},
  {"name":"John McEnroe","dob":"16/02/1959","note":"Tennis player","lifePath":6,"destiny":6,"psychic":7},
  {"name":"Ed Sheeran","dob":"17/02/1991","note":"Musician","lifePath":3,"destiny":3,"psychic":8},
  {"name":"Michael Jordan","dob":"17/02/1963","note":"Athlete","lifePath":11,"destiny":2,"psychic":8},
  {"name":"Otto Stern","dob":"17/02/1888","note":"Physicist (Nobel 1943)","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Raphael Peale","dob":"17/02/1774","note":"American painter","lifePath":11,"destiny":2,"psychic":8},
  {"name":"John Travolta","dob":"18/02/1954","note":"Actor (Saturday Night Fever)","lifePath":3,"destiny":3,"psychic":9},
  {"name":"Yoko Ono","dob":"18/02/1933","note":"Aka Mrs John Lennon in Tokyo Japan","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Elie Ducommun","dob":"19/02/1833","note":"Swiss writer & pacifist (Nobel 1902)","lifePath":9,"destiny":9,"psychic":1},
  {"name":"Nicolaus Copernicus","dob":"19/02/1473","note":"Astronomer in Torun - Poland","lifePath":9,"destiny":9,"psychic":1},
  {"name":"Ludwig Eduard Boltzmann","dob":"20/02/1844","note":"Austrian physicist (statistical mechanics)","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Rihanna","dob":"20/02/1988","note":"Musician","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Sidney Poitier","dob":"20/02/1927","note":"Actor (Porgy & Bess & A Raisin in the Sun)","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Andres Segovia","dob":"21/02/1893","note":"Spanish classical guitarist","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Antonio L¢pez de Santa Anna","dob":"21/02/1794","note":"President of Mexico (1833-36)","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Arthur Schopenhauer","dob":"22/02/1788","note":"(the Great Pessimist) German philosopher","lifePath":3,"destiny":3,"psychic":4},
  {"name":"George Washington","dob":"22/02/1732","note":"Statesman","lifePath":1,"destiny":1,"psychic":4},
  {"name":"George Friderick Handel","dob":"23/02/1685","note":"Baroque composer in Germany","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Samuel Pepys","dob":"23/02/1633","note":"Diarist","lifePath":11,"destiny":2,"psychic":5},
  {"name":"Emperor Charles V","dob":"24/02/1500","note":"King of Spain (1516-56)","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Giovanni Pico della Mirandola","dob":"24/02/1463","note":"Italian scholar & Platonist","lifePath":4,"destiny":4,"psychic":6},
  {"name":"Steve Jobs","dob":"24/02/1955","note":"Entrepreneur","lifePath":1,"destiny":1,"psychic":6},
  {"name":"George Harrison","dob":"25/02/1943","note":"Beatle","lifePath":8,"destiny":8,"psychic":7},
  {"name":"John Foster Dulles","dob":"25/02/1888","note":"Secretary of State for President Eisenhower","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Johnny Cash","dob":"26/02/1932","note":"Country singer the Man in Black","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Victor Hugo","dob":"26/02/1802","note":"Author (Hunchback of Notre Dame) in France","lifePath":3,"destiny":3,"psychic":8},
  {"name":"Elizabeth Taylor","dob":"27/02/1932","note":"Actress (Cleopatra) in London - violet eyes","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Ralph Nader","dob":"27/02/1934","note":"Ex-Corvair fan & Consumer advocate","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Linus Pauling","dob":"28/02/1901","note":"Chemist & peace worker (Nobel 1954 & 1962)","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Michel de Montaigne","dob":"28/02/1533","note":"French essayist & philosopher","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Gioachino Rossini","dob":"29/02/1792","note":"Composer of The Barber of Seville and William Tell","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Morarji Desai","dob":"29/02/1896","note":"Former Prime Minister of India","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Frédéric Chopin","dob":"01/03/1810","note":"Composer","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Harriet Tubman","dob":"01/03/1822","note":"Activist","lifePath":8,"destiny":8,"psychic":1},
  {"name":"Harry Belafonte","dob":"01/03/1927","note":"Singer, Actor","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Ryunosuke Akutagawa","dob":"01/03/1892","note":"Japan, writer (Rashomon in Kappa)","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Dr. Seuss","dob":"02/03/1904","note":"Author (Horton Hears a Who!)","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Mikhail Gorbachev","dob":"02/03/1931","note":"Soviet leader","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Alexander Graham Bell","dob":"03/03/1847","note":"Inventor","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Georg Cantor","dob":"03/03/1845","note":"Discovered transfinite numbers (or 1918)","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Antonio Vivaldi","dob":"04/03/1678","note":"Late Baroque violin virtuoso","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Miriam Makeba","dob":"04/03/1932","note":"S African singer","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Andy Gibb","dob":"05/03/1958","note":"Singer, Australia","lifePath":4,"destiny":4,"psychic":5},
  {"name":"Louis I (the Great)","dob":"05/03/1326","note":"King of Hungary (1342-82), Poland (1370-82)","lifePath":11,"destiny":2,"psychic":5},
  {"name":"Alan Greenspan","dob":"06/03/1926","note":"Economist","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Cyrano de Bergerac","dob":"06/03/1619","note":"Famous nose","lifePath":8,"destiny":8,"psychic":6},
  {"name":"Michelangelo","dob":"06/03/1475","note":"Artist","lifePath":8,"destiny":8,"psychic":6},
  {"name":"Maurice Ravel","dob":"07/03/1875","note":"Composer (Bolero), Cibourne, France","lifePath":4,"destiny":4,"psychic":7},
  {"name":"Piet Mondrian","dob":"07/03/1872","note":"Dutch abstract painter (Broadway Boogie Woogie)","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Carl Philipp Emanuel Bach","dob":"08/03/1714","note":"Composer, son of J.S. Bach","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Otto Hahn","dob":"08/03/1879","note":"Co-discovered nuclear fission","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Bobby Fischer","dob":"09/03/1943","note":"World chess champion (1972-75)","lifePath":2,"destiny":2,"psychic":9},
  {"name":"Yuri Gagarin","dob":"09/03/1934","note":"Cosmonaut","lifePath":2,"destiny":2,"psychic":9},
  {"name":"Alexander III","dob":"10/03/1845","note":"Russian tsar (1881-94)","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Arthur Honegger","dob":"10/03/1892","note":"Composer","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Rupert Murdoch","dob":"11/03/1931","note":"Publisher, Australia","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Sir Harold Wilson","dob":"11/03/1916","note":"(Labour), British PM (1964-70, 1974-76)","lifePath":22,"destiny":4,"psychic":2},
  {"name":"George Berkeley","dob":"12/03/1685","note":"Irish philosopher & Bishop of Cloyne","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Liza Minnelli","dob":"12/03/1946","note":"Singer/Actress (Sterile Cuckoo, Cabaret), LA","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Charles","dob":"13/03/1764","note":"Earl Grey, (Whig), British PM (1830-34)","lifePath":7,"destiny":7,"psychic":4},
  {"name":"L. Ron Hubbard","dob":"13/03/1911","note":"Scientologist","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Albert Einstein","dob":"14/03/1879","note":"Physicist","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Billy Crystal","dob":"14/03/1947","note":"Comedian (SNL)","lifePath":11,"destiny":2,"psychic":5},
  {"name":"Andrew Jackson","dob":"15/03/1767","note":"(D), 7th pres (1928-37)","lifePath":3,"destiny":3,"psychic":6},
  {"name":"William Lamb","dob":"15/03/1779","note":"(Whig), Viscount Melbourne, British PM (1834, 1835-41)","lifePath":6,"destiny":6,"psychic":6},
  {"name":"James Madison","dob":"16/03/1751","note":"(D-R), 4th pres (1809-17)","lifePath":6,"destiny":6,"psychic":7},
  {"name":"Jerry Lewis","dob":"16/03/1926","note":"Entertainer, fund raiser, loved in France","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Kalpana Chawla","dob":"17/03/1962","note":"Astronaut","lifePath":2,"destiny":2,"psychic":8},
  {"name":"Kurt Russell","dob":"17/03/1951","note":"Actor","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Rudolf Nureyev","dob":"17/03/1938","note":"Ballet dancer, Russia","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Grover Cleveland","dob":"18/03/1837","note":"22nd & 24th Pres (1885-1889, 1893-1897)","lifePath":4,"destiny":4,"psychic":9},
  {"name":"Neville Chamberlain","dob":"18/03/1869","note":"(C), British PM (1937-40)","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Bruce Willis","dob":"19/03/1955","note":"(Moonlighting)","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Sir Richard Burton","dob":"19/03/1821","note":"Explorer, translator (The Arabian Nights)","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Frederick Winslow Taylor","dob":"20/03/1856","note":"Father of scientific management","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Henrik Ibsen","dob":"20/03/1828","note":"Dramatist (Peer Gynt, Hedda Gabler), Norway","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Johann Sebastian Bach","dob":"21/03/1685","note":"Eisenach, Germany, Composer","lifePath":8,"destiny":8,"psychic":3},
  {"name":"John D. Rockefeller","dob":"21/03/1906","note":"III, billionaire","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Marcel Marceau","dob":"22/03/1923","note":"Mime, France","lifePath":4,"destiny":4,"psychic":4},
  {"name":"William Shatner","dob":"22/03/1931","note":"Mont, (Capt. Kirk, T J Hooker)","lifePath":3,"destiny":3,"psychic":4},
  {"name":"Joan Crawford","dob":"23/03/1908","note":"No wire hangers, ever! (Mildred Pierce)","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Wernher von Braun","dob":"23/03/1912","note":"Wirsitz, Germany, rocket expert","lifePath":3,"destiny":3,"psychic":5},
  {"name":"Harry Houdini","dob":"24/03/1874","note":"Escape artist","lifePath":11,"destiny":2,"psychic":6},
  {"name":"William Morris","dob":"24/03/1834","note":"Engl, artist","lifePath":7,"destiny":7,"psychic":6},
  {"name":"Aretha Franklin","dob":"25/03/1942","note":"Musician","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Elton John","dob":"25/03/1947","note":"Singer - England","lifePath":4,"destiny":4,"psychic":7},
  {"name":"Leonard Nimoy","dob":"26/03/1931","note":"(Spock)","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Pierre Boulez","dob":"26/03/1925","note":"France, composer","lifePath":1,"destiny":1,"psychic":8},
  {"name":"Gloria Swanson","dob":"27/03/1899","note":"Actress (Sadie Thomson, Queen Kelly)","lifePath":3,"destiny":3,"psychic":9},
  {"name":"James Callaghan","dob":"27/03/1912","note":"(Labour), British PM (1976-79)","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Aristide Briand","dob":"28/03/1862","note":"French premier (1909-22) (Nobel 1926)","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Lady Gaga","dob":"28/03/1986","note":"Musician","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Zbigniew Brzezinski","dob":"28/03/1928","note":"National security advisor","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Edward Stanley Earl Derby","dob":"29/03/1799","note":"(C), British PM (1852, 1858-59, 1866-68)","lifePath":22,"destiny":4,"psychic":2},
  {"name":"John Tyler","dob":"29/03/1790","note":"10th Pres (1841-1845)","lifePath":22,"destiny":4,"psychic":2},
  {"name":"Eric Clapton","dob":"30/03/1945","note":"Musician","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Vincent van Gogh","dob":"30/03/1853","note":"Artist","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Christopher Walken","dob":"31/03/1943","note":"Actor, Film And Theatre","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Johann Sebastian Bach","dob":"31/03/1685","note":"Composer","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Nikolai Gogol","dob":"31/03/1809","note":"Father of 19th-century Russian realism (Dead Souls)","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Lon Chaney","dob":"01/04/1883","note":"Man of a thousand faces","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Sergei Rachmaninoff","dob":"01/04/1873","note":"Composer, Music","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Doris Day","dob":"02/04/1924","note":"Girl next door","lifePath":4,"destiny":4,"psychic":2},
  {"name":"Hans Christian Andersen","dob":"02/04/1805","note":"Writer, Language","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Jane Goodall","dob":"03/04/1934","note":"Anthropologist, Social Sciences","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Marlon Brando","dob":"03/04/1924","note":"Godfather","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Heath Ledger","dob":"04/04/1979","note":"Actor, Film And Theatre","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Thaddeus Stevens","dob":"04/04/1792","note":"Notable public figure","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Bette Davis","dob":"05/04/1908","note":"Actor, Film And Theatre","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Peter Greenaway","dob":"05/04/1942","note":"Film Director, Film And Theatre","lifePath":7,"destiny":7,"psychic":5},
  {"name":"Philip Henry Gosse","dob":"06/04/1810","note":"Invented the institutional aquarium","lifePath":11,"destiny":2,"psychic":6},
  {"name":"Rafael Correa","dob":"06/04/1963","note":"Politician, Government","lifePath":11,"destiny":2,"psychic":6},
  {"name":"Billie Holiday","dob":"07/04/1915","note":"Blues singer","lifePath":9,"destiny":9,"psychic":7},
  {"name":"Jackie Chan","dob":"07/04/1954","note":"Actor","lifePath":3,"destiny":3,"psychic":7},
  {"name":"Kofi Annan","dob":"08/04/1938","note":"Diplomat, Government","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Sir Adrian Boult","dob":"08/04/1889","note":"Conductor (BBC Symphony Orchestra)","lifePath":2,"destiny":2,"psychic":8},
  {"name":"Eadweard Muybridge","dob":"09/04/1830","note":"Pioneered study of motion in photography.","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Paul Robeson","dob":"09/04/1898","note":"Singer, Music","lifePath":3,"destiny":3,"psychic":9},
  {"name":"Sean Avery","dob":"10/04/1980","note":"Notable public figure","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Yefim Bronfman","dob":"10/04/1958","note":"Notable public figure","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Dorothy Allison","dob":"11/04/1949","note":"Notable public figure","lifePath":2,"destiny":2,"psychic":2},
  {"name":"Hugh L Carey","dob":"11/04/1919","note":"Notable public figure","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Francis P. Blair","dob":"12/04/1791","note":"Helped found the Republican Party.","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Joschka Fischer","dob":"12/04/1948","note":"Politician, Government","lifePath":11,"destiny":2,"psychic":3},
  {"name":"Christopher Hitchens","dob":"13/04/1949","note":"Journalist, Language","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Thomas Jefferson","dob":"13/04/1743","note":"Statesman","lifePath":5,"destiny":5,"psychic":4},
  {"name":"Arnold Toynbee","dob":"14/04/1889","note":"Historian","lifePath":8,"destiny":8,"psychic":5},
  {"name":"B. R. Ambedkar","dob":"14/04/1891","note":"Jurist","lifePath":1,"destiny":1,"psychic":5},
  {"name":"John Gielgud","dob":"14/04/1904","note":"Actor, Film And Theatre","lifePath":5,"destiny":5,"psychic":5},
  {"name":"Leonardo da Vinci","dob":"15/04/1452","note":"Polymath","lifePath":4,"destiny":4,"psychic":6},
  {"name":"Leonhard Euler","dob":"15/04/1707","note":"Mathematician","lifePath":7,"destiny":7,"psychic":6},
  {"name":"Charlie Chaplin","dob":"16/04/1889","note":"Actor","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Kareem Abdul-Jabbar","dob":"16/04/1947","note":"Tall person","lifePath":5,"destiny":5,"psychic":7},
  {"name":"J.P. Morgan","dob":"17/04/1837","note":"Financed the US.","lifePath":4,"destiny":4,"psychic":8},
  {"name":"Thornton Wilder","dob":"17/04/1897","note":"American novelist","lifePath":1,"destiny":1,"psychic":8},
  {"name":"Clarence Darrow","dob":"18/04/1857","note":"Lawyer","lifePath":7,"destiny":7,"psychic":9},
  {"name":"James Woods","dob":"18/04/1947","note":"Actor, Film And Theatre","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Joseph Estrada","dob":"19/04/1937","note":"Notable public figure","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Ole Evinrude","dob":"19/04/1877","note":"Invented the outboard marine engine.","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Adolf Hitler","dob":"20/04/1889","note":"Politician, Government","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Jessica Lange","dob":"20/04/1949","note":"Actor, Film And Theatre","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Anthony Quinn","dob":"21/04/1915","note":"Actor, Film And Theatre","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Queen Elizabeth II","dob":"21/04/1926","note":"Monarch","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Daniel Day-Lewis","dob":"22/04/1957","note":"Actor, Film And Theatre","lifePath":3,"destiny":3,"psychic":4},
  {"name":"J. Robert Oppenheimer","dob":"22/04/1904","note":"Notable public figure","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Shirley Temple","dob":"23/04/1928","note":"Child","lifePath":11,"destiny":2,"psychic":5},
  {"name":"William Shakespeare","dob":"23/04/1564","note":"Playwright and poet; author of Hamlet and Romeo and Juliet","lifePath":7,"destiny":7,"psychic":5},
  {"name":"Barbra Streisand","dob":"24/04/1942","note":"Profile","lifePath":8,"destiny":8,"psychic":6},
  {"name":"Sachin Tendulkar","dob":"24/04/1973","note":"Athlete","lifePath":3,"destiny":3,"psychic":6},
  {"name":"Willem de Kooning","dob":"24/04/1904","note":"Painter, Fine Arts","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Al Pacino","dob":"25/04/1940","note":"Actor, Film And Theatre","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Guglielmo Marconi","dob":"25/04/1874","note":"Made radio possible","lifePath":4,"destiny":4,"psychic":7},
  {"name":"Charles Richter","dob":"26/04/1900","note":"He tells us how bad the quakes are.","lifePath":4,"destiny":4,"psychic":8},
  {"name":"John James Audubon","dob":"26/04/1785","note":"Birdwatcher","lifePath":6,"destiny":6,"psychic":8},
  {"name":"William Shakespeare","dob":"26/04/1564","note":"Playwright","lifePath":1,"destiny":1,"psychic":8},
  {"name":"Samuel F. B. Morse","dob":"27/04/1791","note":"Notable public figure","lifePath":22,"destiny":4,"psychic":9},
  {"name":"Sergei Prokofiev","dob":"27/04/1891","note":"Composer, Music","lifePath":5,"destiny":5,"psychic":9},
  {"name":"James Monroe","dob":"28/04/1758","note":"5th President (1816-1824)","lifePath":8,"destiny":8,"psychic":1},
  {"name":"Saddam Hussein","dob":"28/04/1937","note":"Politician, Government","lifePath":7,"destiny":7,"psychic":1},
  {"name":"William Randolph Hearst","dob":"29/04/1863","note":"Newspaper publisher (SF Examiner)","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Zubin Mehta","dob":"29/04/1936","note":"Conductor, Music","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Carl Friedrich Gauss","dob":"30/04/1777","note":"One of the greatest mathematician of all time.","lifePath":11,"destiny":2,"psychic":3},
  {"name":"Lars von Trier","dob":"30/04/1956","note":"Film Director, Film And Theatre","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Joseph Addison","dob":"01/05/1672","note":"English essayist (Spectator)","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Pierre Teilhard de Chardin","dob":"01/05/1881","note":"French philosopher, paleontologist","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Alessandro Scarlatti","dob":"02/05/1660","note":"Italian composer","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Theodor Herzl","dob":"02/05/1840","note":"Founder of Zionist movement","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Golda Meir","dob":"03/05/1898","note":"4th Israeli PM (1969-74)","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Pete Seeger","dob":"03/05/1919","note":"Folk singer","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Audrey Hepburn","dob":"04/05/1929","note":"Actor","lifePath":3,"destiny":3,"psychic":4},
  {"name":"Joseph Whitaker","dob":"04/05/1820","note":"English publisher, founded Whitaker's Almanack","lifePath":2,"destiny":2,"psychic":4},
  {"name":"Karl Marx","dob":"05/05/1818","note":"Philosopher","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Spencer Tracy","dob":"05/05/1900","note":"Actor (Guess Who's Coming to Dinner)","lifePath":11,"destiny":2,"psychic":5},
  {"name":"Orson Welles","dob":"06/05/1915","note":"Actor (Citizen Kane, War of the Worlds, Third Man)","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Sigmund Freud","dob":"06/05/1856","note":"Psychologist","lifePath":4,"destiny":4,"psychic":6},
  {"name":"Johannes Brahms","dob":"07/05/1833","note":"Enjoys a good lullaby","lifePath":9,"destiny":9,"psychic":7},
  {"name":"Josip Broz Tito","dob":"07/05/1892","note":"WW II partisan, leader of Yugoslavia (1943-80)","lifePath":5,"destiny":5,"psychic":7},
  {"name":"Pyotr Tchaikovsky","dob":"07/05/1840","note":"Composer","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Rabindranath Tagore","dob":"07/05/1861","note":"Poet","lifePath":1,"destiny":1,"psychic":7},
  {"name":"David Attenborough","dob":"08/05/1926","note":"Environmentalist","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Henri Dunant","dob":"08/05/1828","note":"Of Switzerland, founded Red Cross, YMCA (Nobel 1901)","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Billy Joel","dob":"09/05/1948","note":"Bronx (Pianoman)","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Howard Carter","dob":"09/05/1873","note":"Egyptologist found King Tut","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Fred Astaire","dob":"10/05/1899","note":"Tapdancer","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Gustav Stresemann","dob":"10/05/1878","note":"German chancellor (1923) (Nobel 1926)","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Charles Warren Fairbanks","dob":"11/05/1852","note":"(R), 26th U.S. vice-president (1905-09)","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Irving Berlin","dob":"11/05/1888","note":"Dreaming of a white Christmas","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Florence Nightingale","dob":"12/05/1820","note":"Nurse, Florence, Italy","lifePath":1,"destiny":1,"psychic":3},
  {"name":"George Carlin","dob":"12/05/1937","note":"Comedian","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Peter Gabriel","dob":"13/05/1950","note":"Rocker","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Stevie Wonder","dob":"13/05/1950","note":"Singer","lifePath":6,"destiny":6,"psychic":4},
  {"name":"George Lucas","dob":"14/05/1944","note":"Skywalker","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Mark Zuckerberg","dob":"14/05/1984","note":"Entrepreneur","lifePath":5,"destiny":5,"psychic":5},
  {"name":"Robert Owen","dob":"14/05/1771","note":"English fActory owner, socialist","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Brian Eno","dob":"15/05/1948","note":"Singer","lifePath":33,"destiny":6,"psychic":6},
  {"name":"L. Frank Baum","dob":"15/05/1856","note":"Children's book author (Wizard of Oz)","lifePath":4,"destiny":4,"psychic":6},
  {"name":"Janet Jackson","dob":"16/05/1966","note":"Singer/Michael's sister","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Pierce Brosnan","dob":"16/05/1952","note":"In Israel","lifePath":2,"destiny":2,"psychic":7},
  {"name":"Edward Jenner","dob":"17/05/1749","note":"English physician, discovered vaccination","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Erik Satie","dob":"17/05/1866","note":"Composer","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Bertrand Russell","dob":"18/05/1872","note":"British mathematician, philosopher (Nobel 1950)","lifePath":5,"destiny":5,"psychic":9},
  {"name":"John Paul II","dob":"18/05/1918","note":"264th Roman Catholic pope (1978-, )","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Ho Chi Minh","dob":"19/05/1890","note":"Trail blazer","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Malcolm X","dob":"19/05/1925","note":"Muslim","lifePath":5,"destiny":5,"psychic":1},
  {"name":"John Stuart Mill","dob":"20/05/1806","note":"Philosopher, political economist, Utilitarian","lifePath":4,"destiny":4,"psychic":2},
  {"name":"Moshe Dayan","dob":"20/05/1915","note":"Israeli general & politician","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Albrecht Durer","dob":"21/05/1471","note":"Great German Renaissance painter, print maker","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Alexander Pope","dob":"21/05/1688","note":"Poet (The Rape of the Lock)","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Johann Sebastian Bach","dob":"22/05/1665","note":"In Eisenach, Germany","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Sir Arthur Conan Doyle","dob":"22/05/1859","note":"Brought Sherlock Holmes to life twice","lifePath":5,"destiny":5,"psychic":4},
  {"name":"Friedrich Anton Mesmer","dob":"23/05/1734","note":"German physician, hypnotist","lifePath":7,"destiny":7,"psychic":5},
  {"name":"John Bardeen","dob":"23/05/1908","note":"Physicist (Nobel 1956, 1972)","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Bob Dylan","dob":"24/05/1941","note":"Musician","lifePath":8,"destiny":8,"psychic":6},
  {"name":"Queen Victoria","dob":"24/05/1819","note":"(1837-1901)","lifePath":3,"destiny":3,"psychic":6},
  {"name":"Georgi M. Grechko","dob":"25/05/1932","note":"Soviet cosmonaut (Soyuz 17, 26, T-14)","lifePath":9,"destiny":9,"psychic":7},
  {"name":"Miles Davis","dob":"25/05/1926","note":"Trumpeter, pioneered cool jazz (Porgy and Bess)","lifePath":3,"destiny":3,"psychic":7},
  {"name":"John Wayne","dob":"26/05/1907","note":"Shootist","lifePath":3,"destiny":3,"psychic":8},
  {"name":"Lady Mary Wortley Montagu","dob":"26/05/1689","note":"English essayist, feminist, eccentric","lifePath":1,"destiny":1,"psychic":8},
  {"name":"Christopher Lee","dob":"27/05/1922","note":"Actor","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Vincent Price","dob":"27/05/1911","note":"Actor (The Fly, Laura)","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Ian Fleming","dob":"28/05/1908","note":"Gave James Bond a job (Goldfinger, Dr. No)","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Louis Agassiz","dob":"28/05/1807","note":"Swiss naturalist, geologist, teacher","lifePath":4,"destiny":4,"psychic":1},
  {"name":"John F. Kennedy","dob":"29/05/1917","note":"Statesman","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Oswald Spengler","dob":"29/05/1880","note":"German philosopher (The Decline of the West)","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Patrick Henry","dob":"29/05/1736","note":"American revolutionary leader, orator","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Henry Addington","dob":"30/05/1757","note":"Viscount Sidmouth (C), British PM (1801-04)","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Peter I (the Great)","dob":"30/05/1672","note":"Tsar of Russia (1682-1725)","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Clint Eastwood","dob":"31/05/1930","note":"Actor/mayor (Dirty Harry)","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Manuel I","dob":"31/05/1469","note":"King of Portugal (1495-1521) during era of exploration","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Marilyn Monroe","dob":"01/06/1926","note":"Actor","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Robert Cecil","dob":"01/06/1563","note":"Earl of Salisbury, English chief minister (1598-1625)","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Karl Gjellerup","dob":"02/06/1857","note":"Danish poet, novelist (Nobel 1917)","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Thomas Hardy","dob":"02/06/1840","note":"English poet and novelist (Mayor of Casterbridge)","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Allen Ginsberg","dob":"03/06/1926","note":"Beat poet (Howl)","lifePath":9,"destiny":9,"psychic":3},
  {"name":"William Hone","dob":"03/06/1780","note":"English author, bookseller (The Every-Day Book)","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Fran‡ois Quesnay","dob":"04/06/1694","note":"French economist, leader of the Physiocrats","lifePath":3,"destiny":3,"psychic":4},
  {"name":"John Barrymore","dob":"04/06/1932","note":"Jr., Actor","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Adam Smith","dob":"05/06/1723","note":"Economist (Wealth of Nations) (baptized) Kirkcaldy Scot","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Dennis Gabor","dob":"05/06/1900","note":"Invented holography","lifePath":3,"destiny":3,"psychic":5},
  {"name":"Diego Vel zquez","dob":"06/06/1599","note":"Spanish painter","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Thomas Mann","dob":"06/06/1875","note":"German novelist (Magic Mountain) (Nobel 1929)","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Prince","dob":"07/06/1958","note":"Rocker","lifePath":9,"destiny":9,"psychic":7},
  {"name":"Tom Jones","dob":"07/06/1940","note":"Singer","lifePath":9,"destiny":9,"psychic":7},
  {"name":"Francis Crick","dob":"08/06/1916","note":"Codiscoverer of the structure of DNA (Nobel 1962)","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Frank Lloyd Wright","dob":"08/06/1867","note":"Master builder in Richland Center, Wisc","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Tim Berners-Lee","dob":"08/06/1955","note":"Computer scientist","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Cole Porter","dob":"09/06/1893","note":"Composer, lyricist (Anything Goes, Kiss Me Kate)","lifePath":9,"destiny":9,"psychic":9},
  {"name":"George Stephenson","dob":"09/06/1781","note":"Principal RR locomotive inventor","lifePath":5,"destiny":5,"psychic":9},
  {"name":"Maurice Sendak","dob":"10/06/1928","note":"Children's author, illustrator, set designer","lifePath":9,"destiny":9,"psychic":1},
  {"name":"Saul Bellow","dob":"10/06/1915","note":"Writer, Language","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Gene Wilder","dob":"11/06/1935","note":"Actor (Young Frankenstein, Silver Streak)","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Richard Strauss","dob":"11/06/1864","note":"German composer (Till Eulenspiegel)","lifePath":9,"destiny":9,"psychic":2},
  {"name":"Anne Frank","dob":"12/06/1929","note":"Diarist","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Chick Corea","dob":"12/06/1941","note":"A funky jazz musician","lifePath":6,"destiny":6,"psychic":3},
  {"name":"James Clerk Maxwell","dob":"13/06/1831","note":"Physicist, formulated electromagnetic theory","lifePath":5,"destiny":5,"psychic":4},
  {"name":"William Butler Yeats","dob":"13/06/1865","note":"Irish poet (Wild Swans at Coole) (Nobel 1923)","lifePath":3,"destiny":3,"psychic":4},
  {"name":"Charles-Augustin de Coulomb","dob":"14/06/1736","note":"Physicist, formulated Coulomb's Law","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Che Guevara","dob":"14/06/1928","note":"Revolutionary","lifePath":4,"destiny":4,"psychic":5},
  {"name":"Donald Trump","dob":"14/06/1946","note":"Master Builder","lifePath":4,"destiny":4,"psychic":5},
  {"name":"Edvard Grieg","dob":"15/06/1843","note":"Norwegian composer","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Edward the Black Prince","dob":"15/06/1330","note":"Notable public figure","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Arthur Meighen","dob":"16/06/1874","note":"(C), 9th prime minister of Canada (1920-21, 1926)","lifePath":6,"destiny":6,"psychic":7},
  {"name":"Joyce Carol Oates","dob":"16/06/1938","note":"American novelist (Garden of Earthly Delights)","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Dean Martin","dob":"17/06/1917","note":"Singer, Actor","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Igor Stravinsky","dob":"17/06/1882","note":"Invented Rite of Spring","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Ivan Goncharov","dob":"18/06/1812","note":"Russian novelist, travel writer (Oblomov)","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Paul McCartney","dob":"18/06/1942","note":"Musician","lifePath":22,"destiny":4,"psychic":9},
  {"name":"Blaise Pascal","dob":"19/06/1623","note":"Mathematician, physicist, religious writer","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Malcolm McDowell","dob":"19/06/1943","note":"(Clockwork Orange)","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Cyndi Lauper","dob":"20/06/1953","note":"In Brooklyn - A fun girl","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Errol Flynn","dob":"20/06/1909","note":"Actor","lifePath":9,"destiny":9,"psychic":2},
  {"name":"Benazir Bhutto","dob":"21/06/1953","note":"Pakistani opposition leader","lifePath":9,"destiny":9,"psychic":3},
  {"name":"Jean-Paul Sartre","dob":"21/06/1905","note":"French philosopher, writer (Nobel 1964; declined)","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Kris Kristofferson","dob":"22/06/1936","note":"Singer/Actor (Amerika)","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Meryl Streep","dob":"22/06/1949","note":"Actor","lifePath":33,"destiny":6,"psychic":4},
  {"name":"Alan Turing","dob":"23/06/1912","note":"Computer scientist","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Alfred Kinsey","dob":"23/06/1894","note":"Sexologist","lifePath":33,"destiny":6,"psychic":5},
  {"name":"Ambrose Bierce","dob":"24/06/1842","note":"Satirist","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Lionel Messi","dob":"24/06/1987","note":"Athlete","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Sir Fred Hoyle","dob":"24/06/1915","note":"Cosmologist, proposed steady-state universe theory","lifePath":1,"destiny":1,"psychic":6},
  {"name":"George Michael","dob":"25/06/1963","note":"In England","lifePath":5,"destiny":5,"psychic":7},
  {"name":"Robert Venturi","dob":"25/06/1925","note":"American architect","lifePath":3,"destiny":3,"psychic":7},
  {"name":"Pearl S. Buck","dob":"26/06/1892","note":"Author (The Good Earth) (Nobel 1938)","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Peter Lorre","dob":"26/06/1904","note":"Actor (M, Casablanca, Beast with 5 Fingers)","lifePath":1,"destiny":1,"psychic":8},
  {"name":"Helen Keller","dob":"27/06/1880","note":"Author","lifePath":5,"destiny":5,"psychic":9},
  {"name":"Isabelle Adjani","dob":"27/06/1955","note":"Actor, Film And Theatre","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Elon Musk","dob":"28/06/1971","note":"Entrepreneur","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Mel Brooks","dob":"28/06/1926","note":"Comedian, Actor, director (To Be or Not to Be)","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Peter Paul Rubens","dob":"28/06/1577","note":"Flemish Baroque painter","lifePath":9,"destiny":9,"psychic":1},
  {"name":"Antoine Saint-Exupery","dob":"29/06/1900","note":"French aviator, writer (Wind, Sand & Stars)","lifePath":9,"destiny":9,"psychic":2},
  {"name":"George Washington Goethals","dob":"29/06/1858","note":"Built Panama Canal","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Charles VIII","dob":"30/06/1470","note":"King of France (1483-98), invaded Italy","lifePath":3,"destiny":3,"psychic":3},
  {"name":"William A. Wheeler","dob":"30/06/1819","note":"(R) 19th U.S. vice-president (1877-81)","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Carl Lewis","dob":"01/07/1961","note":"US track and field star.","lifePath":7,"destiny":7,"psychic":1},
  {"name":"George Sand","dob":"01/07/1804","note":"French Romantic novelist (Valentine, Le Figaro).","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Princess Diana","dob":"01/07/1961","note":"Public figure","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Hans Bethe","dob":"02/07/1906","note":"Physicist (Nobel 1967), peace worker.","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Hermann Hesse","dob":"02/07/1877","note":"Swiss novelist, poet (Steppenwolf) (Nobel 1946).","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Franz Kafka","dob":"03/07/1883","note":"Czech, author (Metamorphosis, The Trial, Amerika)","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Louis XI","dob":"03/07/1423","note":"King of France (1461-83).","lifePath":11,"destiny":2,"psychic":3},
  {"name":"Giuseppe Garibaldi","dob":"04/07/1807","note":"Unifier of Italy.","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Nathaniel Hawthorne","dob":"04/07/1804","note":"American author (The Scarlet Letter).","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Andrei Gromyko","dob":"05/07/1909","note":"Diplomat.","lifePath":4,"destiny":4,"psychic":5},
  {"name":"Sir Stamford Raffles","dob":"05/07/1781","note":"Founder of Singapore.","lifePath":2,"destiny":2,"psychic":5},
  {"name":"Dalai Lama","dob":"06/07/1935","note":"Spiritual leader","lifePath":22,"destiny":4,"psychic":6},
  {"name":"Frida Kahlo","dob":"06/07/1907","note":"Artist","lifePath":3,"destiny":3,"psychic":6},
  {"name":"John Paul Jones","dob":"06/07/1747","note":"Naval hero (I have not yet begun to fight).","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Sylvester Stallone","dob":"06/07/1946","note":"(Rocky, Rambo)","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Marc Chagall","dob":"07/07/1887","note":"In Vitebsk Russia, artist","lifePath":2,"destiny":2,"psychic":7},
  {"name":"MS Dhoni","dob":"07/07/1981","note":"Athlete","lifePath":6,"destiny":6,"psychic":7},
  {"name":"Ringo Starr","dob":"07/07/1940","note":"Beatle.","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Count Ferdinand Graf von Zeppelin","dob":"08/07/1838","note":"Inventor","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Vitali I. Sevastyanov","dob":"08/07/1935","note":"Soviet cosmonaut (Soyuz 9, 18).","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Franz Boas","dob":"09/07/1858","note":"Anthropologist, linguist.","lifePath":11,"destiny":2,"psychic":9},
  {"name":"Tom Hanks","dob":"09/07/1956","note":"Actor","lifePath":1,"destiny":1,"psychic":9},
  {"name":"John Calvin","dob":"10/07/1509","note":"Theologian","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Nikola Tesla","dob":"10/07/1856","note":"Inventor","lifePath":1,"destiny":1,"psychic":1},
  {"name":"John Quincy Adams","dob":"11/07/1767","note":"6th Pres (D) (1825-1829) in Braintree, Mass","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Yasonari Kawabata","dob":"11/07/1899","note":"Japanese novelist (Thousand Cranes) (Nobel 1968).","lifePath":9,"destiny":9,"psychic":2},
  {"name":"Bill Cosby","dob":"12/07/1937","note":"Actor, comedian.","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Malala Yousafzai","dob":"12/07/1997","note":"Activist","lifePath":9,"destiny":9,"psychic":3},
  {"name":"Pablo Neruda","dob":"12/07/1904","note":"Chilean poet (Residence on Earth) (Nobel 1971).","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Alexei S. Yeliseyev","dob":"13/07/1934","note":"Soviet cosmonaut (Soyuz 5, 8, 10).","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Harrison Ford","dob":"13/07/1942","note":"(Star Wars, Indiana Jones).","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Ingmar Bergman","dob":"14/07/1918","note":"Film maker (Through a Glass Darkly).","lifePath":4,"destiny":4,"psychic":5},
  {"name":"Isaac Bashevis Singer","dob":"14/07/1904","note":"Yiddish novelist (Enemies) (Nobel 1978).","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Inigo Jones","dob":"15/07/1573","note":"English architect.","lifePath":2,"destiny":2,"psychic":6},
  {"name":"Iris Murdoch","dob":"15/07/1919","note":"Irish novelist.","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Barbara Stanwyck","dob":"16/07/1907","note":"Actress","lifePath":22,"destiny":4,"psychic":7},
  {"name":"Sir Joshua Reynolds","dob":"16/07/1723","note":"English portrait painter.","lifePath":9,"destiny":9,"psychic":7},
  {"name":"Angela Merkel","dob":"17/07/1954","note":"Statesman","lifePath":7,"destiny":7,"psychic":8},
  {"name":"James Cagney","dob":"17/07/1900","note":"Hold that grapefruit.","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Shmuel Agnon","dob":"17/07/1888","note":"Israeli novelist (Day Before Yesterday) (Nobel 1966).","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Gilbert White","dob":"18/07/1720","note":"the father of British naturalists.","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Nelson Mandela","dob":"18/07/1918","note":"Leader","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Priyanka Chopra","dob":"18/07/1982","note":"Actor","lifePath":9,"destiny":9,"psychic":9},
  {"name":"William Makepeace Thackeray","dob":"18/07/1811","note":"Victorian novelist (Vanity Fair).","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Edgar Degas","dob":"19/07/1834","note":"French impressionist painter.","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Vladimir Mayakovsky","dob":"19/07/1893","note":"Soviet poet.","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Carlos Santana","dob":"20/07/1947","note":"Musician.","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Petrarch","dob":"20/07/1304","note":"In Italy, poet","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Ernest Hemingway","dob":"21/07/1899","note":"Writer","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Marshall McLuhan","dob":"21/07/1911","note":"Writer (The Medium is the Massage).","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Robin Williams","dob":"21/07/1952","note":"Actor, comedian (Mork).","lifePath":9,"destiny":9,"psychic":3},
  {"name":"Alexander Calder","dob":"22/07/1898","note":"Sculptor (mobiles, stabiles).","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Gregor Mendel","dob":"22/07/1822","note":"Geneticist who discovered laws of heredity.","lifePath":33,"destiny":6,"psychic":4},
  {"name":"Daniel Radcliffe","dob":"23/07/1989","note":"Actor, Film And Theatre","lifePath":3,"destiny":3,"psychic":5},
  {"name":"James Cardinal Gibbons","dob":"23/07/1834","note":"Notable public figure","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Alexandre Dumas","dob":"24/07/1802","note":"Pre French author.","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Amelia Earhart","dob":"24/07/1898","note":"Into the wild blue yonder","lifePath":3,"destiny":3,"psychic":6},
  {"name":"Simón Bolívar","dob":"24/07/1783","note":"Leader","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Earl Balfour","dob":"25/07/1848","note":"(C), British prime minister (1902-05) and Author.","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Elias Canetti","dob":"25/07/1905","note":"Bulgarian writer (Nobel 1981).","lifePath":2,"destiny":2,"psychic":7},
  {"name":"Carl Jung","dob":"26/07/1875","note":"Psychologist","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Jacinda Ardern","dob":"26/07/1980","note":"Statesman","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Mick Jagger","dob":"26/07/1943","note":"Never gathers moss","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Stanley Kubrick","dob":"26/07/1928","note":"Director (2001, The Shining, A Clockwork Orange).","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Charlotte Corday","dob":"27/07/1768","note":"Assassin of Jean-Paul Marat.","lifePath":11,"destiny":2,"psychic":9},
  {"name":"Giosu Carducci","dob":"27/07/1835","note":"Italian poet (Nobel 1906).","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Beatrix Potter","dob":"28/07/1866","note":"English children's author (Tale of Peter Rabbit).","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Marcel Duchamp","dob":"28/07/1887","note":"Painter (Nude Descending a Staircase).","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Booth Tarkington","dob":"29/07/1869","note":"American novelist (17, Magnificent Ambersons).","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Eyvind Johnson","dob":"29/07/1900","note":"Swedish novelist (Return to Ithaca) (Nobel 1974).","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Henry Ford","dob":"30/07/1863","note":"Entrepreneur","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Henry Moore","dob":"30/07/1898","note":"English sculptor.","lifePath":9,"destiny":9,"psychic":3},
  {"name":"J. K. Rowling","dob":"31/07/1965","note":"Writer","lifePath":5,"destiny":5,"psychic":4},
  {"name":"Jean Dubuffet","dob":"31/07/1901","note":"French painter.","lifePath":22,"destiny":4,"psychic":4},
  {"name":"Milton Friedman","dob":"31/07/1912","note":"Economist.","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Herman Melville","dob":"01/08/1819","note":"American author (Moby Dick, Billy Budd)","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Jean-Baptiste Lamarck","dob":"01/08/1744","note":"Believed in inheritance of acquired traits","lifePath":7,"destiny":7,"psychic":1},
  {"name":"James Baldwin","dob":"02/08/1924","note":"American novelist (Another Country)","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Rmulo Gallegos","dob":"02/08/1884","note":"Venezuelan novelist (Do¤a B rbara), pres. (1948)","lifePath":4,"destiny":4,"psychic":2},
  {"name":"Habib Bourguiba","dob":"03/08/1902","note":"1st president of Tunisia","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Martin Sheen","dob":"03/08/1940","note":"Actor (Subject Was Roses)","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Barack Obama","dob":"04/08/1961","note":"Statesman","lifePath":2,"destiny":2,"psychic":4},
  {"name":"Knut Hamsun","dob":"04/08/1859","note":"Norwegian writer, Nazi (Hunger) (Nobel 1920)","lifePath":8,"destiny":8,"psychic":4},
  {"name":"Percy Bysshe Shelley","dob":"04/08/1792","note":"Poet","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Guy de Maupassant","dob":"05/08/1850","note":"French author","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Neil Armstrong","dob":"05/08/1930","note":"Astronaut","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Lucille Ball","dob":"06/08/1911","note":"NY. comedian, Actress","lifePath":8,"destiny":8,"psychic":6},
  {"name":"Sir Alexander Fleming","dob":"06/08/1881","note":"Cashed in on penicillin (Nobel 1954)","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Carl Ritter","dob":"07/08/1779","note":"Cofounder of modern science of geography","lifePath":3,"destiny":3,"psychic":7},
  {"name":"Lana Cantrell","dob":"07/08/1943","note":"In Sydney Australia","lifePath":5,"destiny":5,"psychic":7},
  {"name":"Andy Warhol","dob":"08/08/1930","note":"Artist, movie producer","lifePath":2,"destiny":2,"psychic":8},
  {"name":"Emiliano Zapata","dob":"08/08/1879","note":"Mexican revolutionary, peasant leader","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Roger Federer","dob":"08/08/1981","note":"Athlete","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Jean Piaget","dob":"09/08/1896","note":"Pioneer developmental psychologist","lifePath":5,"destiny":5,"psychic":9},
  {"name":"Whitney Houston","dob":"09/08/1963","note":"Singer","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Anwar Ibrahim","dob":"10/08/1947","note":"Politician, Government","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Herbert Hoover","dob":"10/08/1874","note":"(R) 31st Pres (1929-1933)","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Sadi Carnot","dob":"11/08/1837","note":"Engineer, French president (1887-94); assassinated","lifePath":2,"destiny":2,"psychic":2},
  {"name":"Steve Wozniak","dob":"11/08/1950","note":"Cofounded Apple Computer","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Jacinto Benavente y Mart¡nez","dob":"12/08/1866","note":"Spanish dramatist (Nobel 1922)","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Robert Southey","dob":"12/08/1774","note":"English poet laureate, biographer of Nelson","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Alfred Hitchcock","dob":"13/08/1899","note":"Director (Psycho, The Birds, Rear Window)","lifePath":3,"destiny":3,"psychic":4},
  {"name":"Felix Wankel","dob":"13/08/1902","note":"German inventor (Wankel rotary-piston engine)","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Halle Berry","dob":"14/08/1966","note":"Actor, Film And Theatre","lifePath":8,"destiny":8,"psychic":5},
  {"name":"John Galsworthy","dob":"14/08/1867","note":"English author (Forsyte Saga) (Nobel 1932)","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Julia Child","dob":"15/08/1912","note":"In Pasadena Calif, chef","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Napoleon Bonaparte","dob":"15/08/1769","note":"Leader","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Madonna","dob":"16/08/1958","note":"Musician","lifePath":2,"destiny":2,"psychic":7},
  {"name":"Menachem Begin","dob":"16/08/1913","note":"Israeli PM (1977-83) (Nobel 1978)","lifePath":2,"destiny":2,"psychic":7},
  {"name":"Ted Hughes","dob":"16/08/1930","note":"English poet laureate (1984-, )","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Pierre de Fermat","dob":"17/08/1601","note":"Mathematician who needed wider margins","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Robert De Niro","dob":"17/08/1943","note":"Actor","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Antonio Salieri","dob":"18/08/1750","note":"Italian composer","lifePath":3,"destiny":3,"psychic":9},
  {"name":"Shelley Winters","dob":"18/08/1922","note":"St Louis Mo Actress","lifePath":22,"destiny":4,"psychic":9},
  {"name":"I$igo L¢pez","dob":"19/08/1398","note":"Marques de Santillana, Spanish poet","lifePath":3,"destiny":3,"psychic":1},
  {"name":"John Dryden","dob":"19/08/1631","note":"1st poet laureate of England (Absalom & Achitophel)","lifePath":2,"destiny":2,"psychic":1},
  {"name":"Orville Wright","dob":"19/08/1871","note":"Aviator","lifePath":8,"destiny":8,"psychic":1},
  {"name":"Benjamin Harrison","dob":"20/08/1833","note":"(R), 23rd Pres (1889-1893) in North Bend, Ohio","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Rajiv Gandhi","dob":"20/08/1944","note":"PM of India (1984-, )","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Aubrey Beardsley","dob":"21/08/1872","note":"English artist (or 0824)","lifePath":2,"destiny":2,"psychic":3},
  {"name":"Matthew Broderick","dob":"21/08/1962","note":"Actor (Ferris Buehler)","lifePath":2,"destiny":2,"psychic":3},
  {"name":"Usain Bolt","dob":"21/08/1986","note":"Athlete","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Claude Debussy","dob":"22/08/1862","note":"Composer (La Mer, Clair de lune)","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Ray Bradbury","dob":"22/08/1920","note":"Sci-fi author (Fahrenheit 451)","lifePath":33,"destiny":6,"psychic":4},
  {"name":"Gene Kelly","dob":"23/08/1912","note":"Dancer/Actor","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Louis XVI","dob":"23/08/1754","note":"King of France (1774-92); guillotined","lifePath":3,"destiny":3,"psychic":5},
  {"name":"Fernand Braudel","dob":"24/08/1902","note":"French historian","lifePath":8,"destiny":8,"psychic":6},
  {"name":"Jorge Luis Borges","dob":"24/08/1899","note":"Argentine writer of fiction & essays","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Leonard Bernstein","dob":"25/08/1918","note":"Conductor-composer","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Sean Connery","dob":"25/08/1930","note":"Actor (James Bond, Man Who Would Be King)","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Guillaume Apollinaire","dob":"26/08/1880","note":"French poet","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Mother Teresa","dob":"26/08/1910","note":"Humanitarian","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Sir Robert Walpole","dob":"26/08/1676","note":"(Whig), British prime minister, 1721-42","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Mother Teresa","dob":"27/08/1910","note":"Of Calcutta (Nobel 1979)","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Theodore Dreiser","dob":"27/08/1871","note":"Novelist (Sister Carie, An American Tragedy)","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Johann Wolfgang von Goethe","dob":"28/08/1749","note":"Frankfurt, social philosopher (Faust)","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Leo Tolstoy","dob":"28/08/1828","note":"Writer, social philosopher (War & Peace)","lifePath":1,"destiny":1,"psychic":1},
  {"name":"John Locke","dob":"29/08/1632","note":"British empiricist philosopher","lifePath":22,"destiny":4,"psychic":2},
  {"name":"Michael Jackson","dob":"29/08/1958","note":"Musician","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Ernest Rutherford","dob":"30/08/1871","note":"In Engl, phycist","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Mary Shelley","dob":"30/08/1797","note":"Author (Frankenstein)","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Maria Montessori","dob":"31/08/1870","note":"Educator","lifePath":1,"destiny":1,"psychic":4},
  {"name":"William Saroyan","dob":"31/08/1908","note":"Novelist, playwright (Time of Your Life)","lifePath":3,"destiny":3,"psychic":4},
  {"name":"Engelbert Humperdinck","dob":"01/09/1854","note":"German opera composer","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Rocky Marciano","dob":"01/09/1923","note":"Boxer","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Queen Liliuokalani","dob":"02/09/1838","note":"Last queen of Hawaii (1891-93)","lifePath":4,"destiny":4,"psychic":2},
  {"name":"Wilhelm Ostwald","dob":"02/09/1853","note":"German physical chemist (Nobel 1909)","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Charlie Sheen","dob":"03/09/1965","note":"Actor, Film And Theatre","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Nicolo Amati","dob":"03/09/1596","note":"Italian violin maker","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Anton Bruckner","dob":"04/09/1824","note":"In Austria, Wagner disciple","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Beyoncé","dob":"04/09/1981","note":"Musician","lifePath":5,"destiny":5,"psychic":4},
  {"name":"Darius Milhaud","dob":"04/09/1872","note":"Composer","lifePath":22,"destiny":4,"psychic":4},
  {"name":"Arthur Koestler","dob":"05/09/1905","note":"Hungarian-born writer (Darkness at Noon)","lifePath":2,"destiny":2,"psychic":5},
  {"name":"Freddie Mercury","dob":"05/09/1946","note":"Musician","lifePath":7,"destiny":7,"psychic":5},
  {"name":"John Cage","dob":"05/09/1912","note":"Composer (Silence)","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Jane Addams","dob":"06/09/1860","note":"American pacifist/social worker/feminist (Nobel 1931)","lifePath":3,"destiny":3,"psychic":6},
  {"name":"John Dalton","dob":"06/09/1766","note":"Chemist, developed atomic theory of matter","lifePath":8,"destiny":8,"psychic":6},
  {"name":"Buddy Holly","dob":"07/09/1936","note":"Singer (Peggy Sue, That'll Be the Day)","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Elia Kazan","dob":"07/09/1909","note":"Film Director, Film And Theatre","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Anton¡n Dvor k","dob":"08/09/1841","note":"In Nelahozeves, Czech, composer (New World Symphony)","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Peter Sellers","dob":"08/09/1925","note":"(not now, Kato)","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Cardinal de Richelieu","dob":"09/09/1585","note":"Chief minister to Louis XIII of France","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Leo Tolstoy","dob":"09/09/1828","note":"Writer","lifePath":1,"destiny":1,"psychic":9},
  {"name":"William Cranch Bond","dob":"09/09/1789","note":"American astronomer, codiscover of Hyperion","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Franz Werfel","dob":"10/09/1890","note":"Austrian author (40 Days of Musa Dagh)","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Isaac Kauffman Funk","dob":"10/09/1839","note":"American publisher (Funk & Wagnalls)","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Ferdinand Marcos","dob":"11/09/1917","note":"Former Philippines Pres","lifePath":11,"destiny":2,"psychic":2},
  {"name":"O. Henry","dob":"11/09/1862","note":"Pen name of William Sidney Porter, short story writer","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Jesse Owens","dob":"12/09/1913","note":"Spoiled Hitler's 1936 Olympics","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Maurice Chevalier","dob":"12/09/1888","note":"Thanked heaven for little girls (Gigi)","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Arnold Schoenberg","dob":"13/09/1874","note":"Composer","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Sherwood Anderson","dob":"13/09/1876","note":"American author, publisher (Winesburg, Ohio)","lifePath":8,"destiny":8,"psychic":4},
  {"name":"Albert Shanker","dob":"14/09/1928","note":"American labor leader","lifePath":7,"destiny":7,"psychic":5},
  {"name":"Ivan Pavlov","dob":"14/09/1849","note":"Russian physiologist, pioneer in psychology","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Agatha Christie","dob":"15/09/1890","note":"Writer","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Porfirio D¡az","dob":"15/09/1830","note":"Soldier, president of Mexico (1877-1911)","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Tommy Lee Jones","dob":"15/09/1946","note":"Actor","lifePath":8,"destiny":8,"psychic":6},
  {"name":"A Bonar Law","dob":"16/09/1858","note":"(C), British prime minister (1922-23)","lifePath":11,"destiny":2,"psychic":7},
  {"name":"Lauren Bacall","dob":"16/09/1924","note":"In Staten Island (Dark Passage, Key Largo)","lifePath":5,"destiny":5,"psychic":7},
  {"name":"Hank Williams","dob":"17/09/1923","note":"Country singer (Cold, Cold Heart, Hey Good Lookin')","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Konstantin Tsiolkovsky","dob":"17/09/1857","note":"Pioneer in rocket & space research","lifePath":2,"destiny":2,"psychic":8},
  {"name":"Narendra Modi","dob":"17/09/1950","note":"Statesman","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Dr Samuel Johnson","dob":"18/09/1709","note":"Boswell's tour guide, writer","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Greta Garbo","dob":"18/09/1905","note":"In Stockholm (Ninotchka, Grand Hotel)","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Jan Luyts","dob":"19/09/1655","note":"Dutch scholar, physicist, mathematician, astronomer","lifePath":9,"destiny":9,"psychic":1},
  {"name":"Jeremy Irons","dob":"19/09/1948","note":"English Actor (French Lieutenant's Woman)","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Jean Racine","dob":"20/09/1978","note":"Writer, Language","lifePath":9,"destiny":9,"psychic":2},
  {"name":"Sophia Loren","dob":"20/09/1934","note":"Rome (Desire Under the Elms, Black Orchid)","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Girolamo Savonarola","dob":"21/09/1452","note":"Florentine monk, preacher, reformer","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Stephen King","dob":"21/09/1947","note":"Suspense writer (Shining, Kujo)","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Michael Faraday","dob":"22/09/1791","note":"Discovered principle of electric motor","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Shigeru Yoshida","dob":"22/09/1878","note":"Japanese PM (most of 1946-54)","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Augustus","dob":"23/09/1583","note":"Politician, Government","lifePath":22,"destiny":4,"psychic":5},
  {"name":"Ray Charles","dob":"23/09/1930","note":"Sings Georgia, entertainer","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Horace Walpole","dob":"24/09/1717","note":"English writer","lifePath":22,"destiny":4,"psychic":6},
  {"name":"John Marshall","dob":"24/09/1755","note":"Supreme Court Chief Justice","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Christopher Reeve","dob":"25/09/1952","note":"Actor (Superman)","lifePath":6,"destiny":6,"psychic":7},
  {"name":"Mark Rothko","dob":"25/09/1903","note":"Painter","lifePath":2,"destiny":2,"psychic":7},
  {"name":"George Gershwin","dob":"26/09/1898","note":"Bkln, composer (Rhapsody in Blue)","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Paul VI","dob":"26/09/1897","note":"262nd Roman Catholic pope (1963-78)","lifePath":6,"destiny":6,"psychic":8},
  {"name":"Serena Williams","dob":"26/09/1981","note":"Athlete","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Samuel Adams","dob":"27/09/1722","note":"Revolutionary rabble rouser","lifePath":3,"destiny":3,"psychic":9},
  {"name":"Sir Martin Ryle","dob":"27/09/1918","note":"British radio astronomer, astronomer royal 1972-82","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Confucius","dob":"28/09/1912","note":"Philosopher, Philosophy","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Max Schmeling","dob":"28/09/1905","note":"Of Germany, world heavyweight boxing champ (1930-32)","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Enrico Fermi","dob":"29/09/1901","note":"Physicist, gone fission","lifePath":4,"destiny":4,"psychic":2},
  {"name":"Jerry Lee Lewis","dob":"29/09/1935","note":"Singer (Great Balls of Fire, Breathless)","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Elie Wiesel","dob":"30/09/1928","note":"Author (Souls on Fire), Nazi hunter (Nobel 1986)","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Truman Capote","dob":"30/09/1924","note":"A short short story writer (In Cold Blood)","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Julie Andrews","dob":"01/10/1935","note":"Actress & singer (Sound of Music, Mary Poppins)","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Vladimir Horowitz","dob":"01/10/1904","note":"Pianist","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Groucho Marx","dob":"02/10/1895","note":"Comedian","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Mahatma Gandhi","dob":"02/10/1869","note":"Leader","lifePath":9,"destiny":9,"psychic":2},
  {"name":"Sting","dob":"02/10/1951","note":"(Police)","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Gore Vidal","dob":"03/10/1925","note":"Writer (Myra Breckinridge, Lincoln)","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Mikhail Lermontov","dob":"03/10/1814","note":"Leading Russian Romantic poet, novelist","lifePath":9,"destiny":9,"psychic":3},
  {"name":"Louis X","dob":"04/10/1289","note":"(the Stubborn), king of France (1314-16)","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Susan Sarandon","dob":"04/10/1946","note":"NYC (Atlantic City, Great Waldo Pepper)","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Denis Diderot","dob":"05/10/1713","note":"Encyclopedist","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Richard F. Gordon Jr.","dob":"05/10/1929","note":"U.S. astronaut (Gemini 11, Apollo 12)","lifePath":9,"destiny":9,"psychic":5},
  {"name":"Jenny Lind","dob":"06/10/1820","note":"In Sweden, soprano, nightingale","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Richard Dedekind","dob":"06/10/1831","note":"Mathematician","lifePath":11,"destiny":2,"psychic":6},
  {"name":"Desmond Tutu","dob":"07/10/1931","note":"Archbishop of South Africa","lifePath":4,"destiny":4,"psychic":7},
  {"name":"Yo-Yo Ma","dob":"07/10/1955","note":"Cellist","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Bruno Mars","dob":"08/10/1985","note":"Musician","lifePath":5,"destiny":5,"psychic":8},
  {"name":"Ejnar Hertzsprung","dob":"08/10/1873","note":"Danish astronomer (Hertzsprung-Russell diagram)","lifePath":1,"destiny":1,"psychic":8},
  {"name":"Sigourney Weaver","dob":"08/10/1949","note":"LA (Alien)","lifePath":5,"destiny":5,"psychic":8},
  {"name":"John Lennon","dob":"09/10/1940","note":"Musician","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Miguel de Cervantes","dob":"09/10/1547","note":"Novelist (Don Quixote)","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Emily Dickinson","dob":"10/10/1830","note":"Poet","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Giuseppe Verdi","dob":"10/10/1813","note":"Composer of operas (Rigoletto, Aida, Otello)","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Amitabh Bachchan","dob":"11/10/1942","note":"Actor","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Eleanor Roosevelt","dob":"11/10/1884","note":"Crusader","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Francois Mauriac","dob":"11/10/1885","note":"French novelist, poet, playwright (Nobel 1952)","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Luciano Pavarotti","dob":"12/10/1935","note":"Operatic tenor","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Ralph Vaughan Williams","dob":"12/10/1872","note":"In England, composer","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Art Garfunkel","dob":"13/10/1942","note":"Built bridge over troubled waters","lifePath":3,"destiny":3,"psychic":4},
  {"name":"Margaret Thatcher","dob":"13/10/1925","note":"Statesman","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Yves Montand","dob":"13/10/1921","note":"French Actor, singer","lifePath":9,"destiny":9,"psychic":4},
  {"name":"E. E. Cummings","dob":"14/10/1894","note":"Poet","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Roger Moore","dob":"14/10/1926","note":"The 'saintly' James Bond","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Akbar","dob":"15/10/1542","note":"Indian Mughal emperor (1556-1605)","lifePath":1,"destiny":1,"psychic":6},
  {"name":"APJ Abdul Kalam","dob":"15/10/1931","note":"Scientist","lifePath":3,"destiny":3,"psychic":6},
  {"name":"Friedrich Nietzsche","dob":"15/10/1844","note":"Šbermensch","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Enver Hoxha","dob":"16/10/1908","note":"Post-war leader of Albania","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Oscar Wilde","dob":"16/10/1854","note":"(Fingal O'Flahertie Wills) - Dublin, (Pic of Dorian Gray)","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Arthur Miller","dob":"17/10/1915","note":"Playwright (Death of a Salesman, The Crucible)","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Rita Hayworth","dob":"17/10/1919","note":"In NY (Alzheimer victim)","lifePath":11,"destiny":2,"psychic":8},
  {"name":"Chuck Berry","dob":"18/10/1926","note":"Rock 'n' roll star","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Henri Bergson","dob":"18/10/1859","note":"French philosopher (Creative Evolution) (Nobel 1927)","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Christopher Wren","dob":"19/10/1632","note":"English astronomer & architect","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Subrahmanyan Chandrasekhar","dob":"19/10/1910","note":"Indian physicist (Nobel 1983)","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Arthur Rimbaud","dob":"20/10/1854","note":"French poet, adventurer (Illuminations)","lifePath":3,"destiny":3,"psychic":2},
  {"name":"John Dewey","dob":"20/10/1859","note":"Philosopher","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Carrie Fisher","dob":"21/10/1956","note":"In Beverly Hills - Star Wars' Princess Lelia","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Samuel Taylor Coleridge","dob":"21/10/1772","note":"In England, poet","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Franz Liszt","dob":"22/10/1811","note":"Hungary, Romantic composer, virtuoso pianist","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Jeff Goldblum","dob":"22/10/1952","note":"Actor","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Ang Lee","dob":"23/10/1954","note":"Film Director, Film And Theatre","lifePath":7,"destiny":7,"psychic":5},
  {"name":"Johnny Carson","dob":"23/10/1925","note":"Tonight Show host","lifePath":5,"destiny":5,"psychic":5},
  {"name":"Pelé","dob":"23/10/1940","note":"Athlete","lifePath":11,"destiny":2,"psychic":5},
  {"name":"Antony van Leeuwenhoek","dob":"24/10/1632","note":"Dutch naturalist","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Drake","dob":"24/10/1986","note":"Musician","lifePath":4,"destiny":4,"psychic":6},
  {"name":"Kevin Kline","dob":"24/10/1947","note":"Actor, Film And Theatre","lifePath":1,"destiny":1,"psychic":6},
  {"name":"Georges Bizet","dob":"25/10/1838","note":"Composer","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Pablo Picasso","dob":"25/10/1881","note":"Artist","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Desiderius Erasmus","dob":"26/10/1466","note":"Dutch scholar, author of The Praise of Folly","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Georges Danton","dob":"26/10/1759","note":"French Revolutionary leader","lifePath":4,"destiny":4,"psychic":8},
  {"name":"John Cleese","dob":"27/10/1939","note":"(Monty Python, Fawlty Towers)","lifePath":5,"destiny":5,"psychic":9},
  {"name":"Theodore Roosevelt","dob":"27/10/1858","note":"26th Pres (1901-09) (Nobel 1906)","lifePath":5,"destiny":5,"psychic":9},
  {"name":"Bill Gates","dob":"28/10/1955","note":"Entrepreneur","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Cornelius Otto Jansen","dob":"28/10/1585","note":"Of France, Roman Catholic reform leader","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Dr Jonas Salk","dob":"28/10/1914","note":"Who made polio a fear of the past","lifePath":8,"destiny":8,"psychic":1},
  {"name":"Edmund Halley","dob":"29/10/1656","note":"In London","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Guillermo Valencia","dob":"29/10/1873","note":"Colombian poet, translator, statesman","lifePath":4,"destiny":4,"psychic":2},
  {"name":"Diego Maradona","dob":"30/10/1960","note":"Athlete","lifePath":11,"destiny":2,"psychic":3},
  {"name":"John Adams","dob":"30/10/1735","note":"(F), 2nd pres (1797-1801) in Braintree, Mass","lifePath":11,"destiny":2,"psychic":3},
  {"name":"Paul Valery","dob":"30/10/1871","note":"French poet, essayist, critic","lifePath":3,"destiny":3,"psychic":3},
  {"name":"John Keats","dob":"31/10/1795","note":"Romantic poet","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Karl Weierstrass","dob":"31/10/1815","note":"German mathematician (theory of functions)","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Sardar Patel","dob":"31/10/1875","note":"Statesman","lifePath":8,"destiny":8,"psychic":4},
  {"name":"Aishwarya Rai","dob":"01/11/1973","note":"Actor","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Martin Luther","dob":"01/11/1699","note":"Protestant reformer","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Stephen Crane","dob":"01/11/1871","note":"Poet (Red Badge of Courage)","lifePath":2,"destiny":2,"psychic":1},
  {"name":"George Boole","dob":"02/11/1815","note":"Mathematician","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Harlow Shapley","dob":"02/11/1885","note":"US astronomer","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Shah Rukh Khan","dob":"02/11/1965","note":"Actor","lifePath":7,"destiny":7,"psychic":2},
  {"name":"John Montague","dob":"03/11/1718","note":"4th Earl of Sandwich, inventor of same","lifePath":22,"destiny":4,"psychic":3},
  {"name":"Karl Baedeker","dob":"03/11/1801","note":"German publisher of travel books","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Eden Phillpotts","dob":"04/11/1862","note":"English novelist, poet, playwright","lifePath":5,"destiny":5,"psychic":4},
  {"name":"Walter Cronkite","dob":"04/11/1916","note":"Newsman (and that's the way it is)","lifePath":5,"destiny":5,"psychic":4},
  {"name":"Elke Sommer","dob":"05/11/1942","note":"In Berlin Germany","lifePath":5,"destiny":5,"psychic":5},
  {"name":"Paul Simon","dob":"05/11/1942","note":"Singer, songwriter (Bridge Over Troubled Waters)","lifePath":5,"destiny":5,"psychic":5},
  {"name":"Virat Kohli","dob":"05/11/1988","note":"Athlete","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Heinrich Himmler","dob":"06/11/1900","note":"Nazi SS leader","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Marie Curie","dob":"06/11/1867","note":"Discoverer of radium","lifePath":3,"destiny":3,"psychic":6},
  {"name":"Albert Camus","dob":"07/11/1913","note":"French novelist, playwright (Plauge) (Nobel 1957)","lifePath":5,"destiny":5,"psychic":7},
  {"name":"C. V. Raman","dob":"07/11/1888","note":"Scientist","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Joni Mitchell","dob":"07/11/1943","note":"In Alberta Canada, singer (Clouds)","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Marie Curie","dob":"07/11/1867","note":"Scientist","lifePath":4,"destiny":4,"psychic":7},
  {"name":"Gottlob Frege","dob":"08/11/1848","note":"German mathematician, logician, philosopher","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Sir Edmond Halley","dob":"08/11/1656","note":"Astronomer, 1st to calculate a comet's orbit","lifePath":1,"destiny":1,"psychic":8},
  {"name":"Carl Sagan","dob":"09/11/1934","note":"Astronomer, author (Cosmos, Broca's Brain)","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Charles Baudelaire","dob":"09/11/1821","note":"Poet","lifePath":5,"destiny":5,"psychic":9},
  {"name":"Martin Luther","dob":"10/11/1483","note":"In Eisleben, Germany, founder of Protestantism","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Richard Burton","dob":"10/11/1925","note":"Welsh Actor (Cleopatra, Virginia Woolf)","lifePath":2,"destiny":2,"psychic":1},
  {"name":"Demi Moore","dob":"11/11/1963","note":"Actor, Film And Theatre","lifePath":5,"destiny":5,"psychic":2},
  {"name":"Fyodor Dostoyevsky","dob":"11/11/1821","note":"Russian author (Crime and Punishment)","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Leonardo DiCaprio","dob":"11/11/1974","note":"Actor","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Grace Kelly","dob":"12/11/1929","note":"Princess of Monaco in Phila","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Neil Young","dob":"12/11/1945","note":"Canadian singer, songwriter","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Edwin Booth","dob":"13/11/1833","note":"American Actor","lifePath":3,"destiny":3,"psychic":4},
  {"name":"Robert Louis Stevenson","dob":"13/11/1850","note":"Scottish author (Treasure Island)","lifePath":2,"destiny":2,"psychic":4},
  {"name":"Claude Monet","dob":"14/11/1840","note":"Artist","lifePath":2,"destiny":2,"psychic":5},
  {"name":"Jawaharlal Nehru","dob":"14/11/1889","note":"Statesman","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Erwin Rommel","dob":"15/11/1891","note":"German field marshall","lifePath":9,"destiny":9,"psychic":6},
  {"name":"Petula Clark","dob":"15/11/1932","note":"In England","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Paul Hindemith","dob":"16/11/1895","note":"In Germany, composer","lifePath":5,"destiny":5,"psychic":7},
  {"name":"Rodolphe Kreutzer","dob":"16/11/1766","note":"French composer, virtuoso violinist","lifePath":2,"destiny":2,"psychic":7},
  {"name":"Joost van den Vondel","dob":"17/11/1587","note":"Dutch poet, dramatist","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Martin Scorsese","dob":"17/11/1942","note":"Director (Mean Streets, NY, NY)","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Amelita Galli-Curci","dob":"18/11/1889","note":"Italian operatic soprano","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Louis-Jacques-Mande Daguerre","dob":"18/11/1789","note":"Developed a method of photography","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Indira Gandhi","dob":"19/11/1917","note":"Statesman","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Jodie Foster","dob":"19/11/1962","note":"LA (Bugsy Malone) - Pulls Hinckley's string","lifePath":3,"destiny":3,"psychic":1},
  {"name":"Edwin Hubble","dob":"20/11/1889","note":"US astronomer, discoverer of galaxies, red shift","lifePath":3,"destiny":3,"psychic":2},
  {"name":"Joe Biden","dob":"20/11/1942","note":"Statesman","lifePath":2,"destiny":2,"psychic":2},
  {"name":"Nadine Gordimer","dob":"20/11/1923","note":"South African writer (Lying Days)","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Benedict XV","dob":"21/11/1854","note":"258th Roman Catholic pope (1914-22)","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Jamie Lee Curtis","dob":"21/11/1958","note":"Actress (Halloween, Trading Places)","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Charles de Gaulle","dob":"22/11/1890","note":"Pres of France (1958-69)","lifePath":6,"destiny":6,"psychic":4},
  {"name":"Jamie Lee Curtis","dob":"22/11/1958","note":"In LA, Cal - Tony Curtis & Janet Leigh's daughter","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Boris Karloff","dob":"23/11/1887","note":"Bogeyman (Frankenstein, Isle of the Dead)","lifePath":22,"destiny":4,"psychic":5},
  {"name":"Franklin Pierce","dob":"23/11/1804","note":"14th Pres (1853-1857)","lifePath":2,"destiny":2,"psychic":5},
  {"name":"Baruch Spinoza","dob":"24/11/1632","note":"Philosopher","lifePath":2,"destiny":2,"psychic":6},
  {"name":"Dale Carnegie","dob":"24/11/1888","note":"Author (How to Win Friends and Influence People)","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Andrew Carnegie","dob":"25/11/1835","note":"Steel industrialist, library builder","lifePath":8,"destiny":8,"psychic":7},
  {"name":"Tina Turner","dob":"25/11/1940","note":"In Brownsville Tx","lifePath":5,"destiny":5,"psychic":7},
  {"name":"Ferdinand de Saussure","dob":"26/11/1857","note":"Swiss linguist","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Tina Turner","dob":"26/11/1938","note":"Singer","lifePath":22,"destiny":4,"psychic":8},
  {"name":"Bruce Lee","dob":"27/11/1940","note":"Martial artist","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Fanny Kemble","dob":"27/11/1809","note":"English Actress","lifePath":11,"destiny":2,"psychic":9},
  {"name":"Jimi Hendrix","dob":"27/11/1942","note":"Guitarist","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Friedrich Engels","dob":"28/11/1820","note":"Marx's collaborator","lifePath":5,"destiny":5,"psychic":1},
  {"name":"William Blake","dob":"28/11/1757","note":"Poet (Songs of Innocence and Experience)","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Christian Doppler","dob":"29/11/1803","note":"Discovered Doppler Effect (color shift)","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Paul Simon","dob":"29/11/1928","note":"(Sen-D-Ill), pres candidate","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Jonathan Swift","dob":"30/11/1667","note":"Satirist (Gulliver's Travels, A Modest Proposal)","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Mark Twain","dob":"30/11/1835","note":"Writer","lifePath":22,"destiny":4,"psychic":3},
  {"name":"Sir Winston Churchill","dob":"30/11/1874","note":"(C), Brit. PM (1940-45, 1951-55) (Nobel 1953)","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Winston Churchill","dob":"30/11/1874","note":"Statesman","lifePath":7,"destiny":7,"psychic":3},
  {"name":"Mih ly Vorosmarty","dob":"01/12/1800","note":"Hungarian poet, dramatist","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Woody Allen","dob":"01/12/1935","note":"(Allen Stuart Konigsberg) Bkln (Zelig, Annie Hall)","lifePath":4,"destiny":4,"psychic":1},
  {"name":"Georges Seurat","dob":"02/12/1859","note":"French painter, pointillist","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Maria Callas","dob":"02/12/1923","note":"NY opera singer","lifePath":11,"destiny":2,"psychic":2},
  {"name":"Jim Morrison","dob":"03/12/1943","note":"Rock musician (Doors)","lifePath":5,"destiny":5,"psychic":3},
  {"name":"Ozzy Osbourne","dob":"03/12/1948","note":"Eat a bat","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Pope Julius II","dob":"04/12/1443","note":"(1503-13), patron of Michelangelo, Bramante, Raphael","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Rainer Maria Rilke","dob":"04/12/1875","note":"German poet (Duino Elegies)","lifePath":1,"destiny":1,"psychic":4},
  {"name":"Martin Van Buren","dob":"05/12/1782","note":"(D), 8th pres (1837-41)","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Walt Disney","dob":"05/12/1901","note":"Entrepreneur","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Werner Heisenberg","dob":"05/12/1901","note":"Discoverer of uncertainty (Nobel 1932)","lifePath":1,"destiny":1,"psychic":5},
  {"name":"Gunnar Myrdal","dob":"06/12/1898","note":"Swedish sociologist, economist","lifePath":8,"destiny":8,"psychic":6},
  {"name":"John Eberhard","dob":"06/12/1822","note":"Built 1st large US pencil fActory","lifePath":4,"destiny":4,"psychic":6},
  {"name":"Akiko Yosano","dob":"07/12/1878","note":"Japanese poet","lifePath":7,"destiny":7,"psychic":7},
  {"name":"Larry Bird","dob":"07/12/1956","note":"(Boston Celtics)","lifePath":4,"destiny":4,"psychic":7},
  {"name":"Aristide Maillol","dob":"08/12/1861","note":"French painter, sculptor","lifePath":9,"destiny":9,"psychic":8},
  {"name":"Jean Sibelius","dob":"08/12/1865","note":"Major Scandinavian composer","lifePath":4,"destiny":4,"psychic":8},
  {"name":"John Milton","dob":"09/12/1608","note":"Poet and puritan (Paradise Lost)","lifePath":9,"destiny":9,"psychic":9},
  {"name":"Kirk Douglas","dob":"09/12/1918","note":"Actor (Gunfight at the OK Corral, 7 Days in May)","lifePath":4,"destiny":4,"psychic":9},
  {"name":"Ada Lovelace","dob":"10/12/1815","note":"Mathematician","lifePath":1,"destiny":1,"psychic":1},
  {"name":"Cesar Franck","dob":"10/12/1822","note":"In Belgium, composer","lifePath":8,"destiny":8,"psychic":1},
  {"name":"Emily Dickinson","dob":"10/12/1830","note":"Poet","lifePath":7,"destiny":7,"psychic":1},
  {"name":"Aleksandr Solzhenitsyn","dob":"11/12/1918","note":"Russian writer (Cancer Ward) (Nobel 1970)","lifePath":6,"destiny":6,"psychic":2},
  {"name":"Hector Berlioz","dob":"11/12/1803","note":"In France, composer","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Edvard Munch","dob":"12/12/1863","note":"Norwegian painter and print maker (The Scream)","lifePath":6,"destiny":6,"psychic":3},
  {"name":"Frank Sinatra","dob":"12/12/1915","note":"Singer, Actor (Old Blue Eyes)","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Rajinikanth","dob":"12/12/1950","note":"Actor","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Heinrich Heine","dob":"13/12/1797","note":"German poet","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Mary Todd Lincoln","dob":"13/12/1818","note":"1st lady","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Taylor Swift","dob":"13/12/1989","note":"Musician","lifePath":7,"destiny":7,"psychic":4},
  {"name":"Nostradamus","dob":"14/12/1503","note":"Astrologer and physician","lifePath":8,"destiny":8,"psychic":5},
  {"name":"Tycho Brahe","dob":"14/12/1546","note":"At Knudstrup, Denmark, astronomer","lifePath":6,"destiny":6,"psychic":5},
  {"name":"Alexandre-Gustave Eiffel","dob":"15/12/1832","note":"Built a tower in Paris","lifePath":5,"destiny":5,"psychic":6},
  {"name":"Charles Edgar Duryea","dob":"15/12/1861","note":"Invented 1st auto built and operated in US","lifePath":7,"destiny":7,"psychic":6},
  {"name":"Catherine of Aragon","dob":"16/12/1485","note":"1st wife of Henry VIII","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Jane Austen","dob":"16/12/1775","note":"Writer","lifePath":3,"destiny":3,"psychic":7},
  {"name":"Joseph Henry","dob":"17/12/1797","note":"American scientist and inventor","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Ludwig van Beethoven","dob":"17/12/1770","note":"Composer","lifePath":8,"destiny":8,"psychic":8},
  {"name":"Pope Francis","dob":"17/12/1936","note":"Religious leader","lifePath":3,"destiny":3,"psychic":8},
  {"name":"Sir Humphry Davy","dob":"17/12/1778","note":"Discovered several chemical elements","lifePath":7,"destiny":7,"psychic":8},
  {"name":"Paul Klee","dob":"18/12/1879","note":"Swiss abstract painter","lifePath":1,"destiny":1,"psychic":9},
  {"name":"Steven Spielberg","dob":"18/12/1947","note":"Director (Jaws, Raiders of the Lost Arc)","lifePath":6,"destiny":6,"psychic":9},
  {"name":"Jennifer Beals","dob":"19/12/1963","note":"In Chicago (Flashdance)","lifePath":5,"destiny":5,"psychic":1},
  {"name":"Leonid Brezhnev","dob":"19/12/1906","note":"Ukraine","lifePath":11,"destiny":2,"psychic":1},
  {"name":"Ferdinand-douard Buisson","dob":"20/12/1841","note":"French educator (Nobel Peace Prize 1927)","lifePath":1,"destiny":1,"psychic":2},
  {"name":"Sir Robert Menzies","dob":"20/12/1894","note":"Australian PM (1939-41, 1949-66)","lifePath":9,"destiny":9,"psychic":2},
  {"name":"Emmanuel Macron","dob":"21/12/1977","note":"Statesman","lifePath":3,"destiny":3,"psychic":3},
  {"name":"Frank Zappa","dob":"21/12/1940","note":"Rock singer (Grateful Dead)","lifePath":11,"destiny":2,"psychic":3},
  {"name":"Joseph Stalin","dob":"21/12/1879","note":"Russian dictator","lifePath":4,"destiny":4,"psychic":3},
  {"name":"Giacomo Puccini","dob":"22/12/1858","note":"Italian operatic composer (La Bohme, Tosca)","lifePath":11,"destiny":2,"psychic":4},
  {"name":"James Oglethorpe","dob":"22/12/1696","note":"English general, author, colonizer of Georgia","lifePath":11,"destiny":2,"psychic":4},
  {"name":"Srinivasa Ramanujan","dob":"22/12/1887","note":"Mathematician","lifePath":4,"destiny":4,"psychic":4},
  {"name":"Alexander I","dob":"23/12/1777","note":"Tsar of Russia (1801-25)","lifePath":3,"destiny":3,"psychic":5},
  {"name":"Sir Richard Arkwright","dob":"23/12/1732","note":"Invented spinning frame","lifePath":3,"destiny":3,"psychic":5},
  {"name":"Madonna","dob":"24/12/1959","note":"Rock singer, Actress (Desperately Seeking Susan)","lifePath":6,"destiny":6,"psychic":6},
  {"name":"Matthew Arnold","dob":"24/12/1822","note":"English poet (Dover Beach)","lifePath":4,"destiny":4,"psychic":6},
  {"name":"Isaac Newton","dob":"25/12/1642","note":"(sir) in Grantham, England","lifePath":5,"destiny":5,"psychic":7},
  {"name":"Joseph McCarthy","dob":"25/12/1881","note":"Yank manager","lifePath":1,"destiny":1,"psychic":7},
  {"name":"Charles Babbage","dob":"26/12/1792","note":"Invented calculating machine","lifePath":3,"destiny":3,"psychic":8},
  {"name":"Henry Miller","dob":"26/12/1891","note":"Author (Tropic of Capricorn, Tropic of Cancer)","lifePath":3,"destiny":3,"psychic":8},
  {"name":"Johannes Kepler","dob":"27/12/1571","note":"At Weil-der-Stadt, Germany, Astronomer","lifePath":8,"destiny":8,"psychic":9},
  {"name":"Louis Pasteur","dob":"27/12/1822","note":"French bacteriologist","lifePath":7,"destiny":7,"psychic":9},
  {"name":"Dhirubhai Ambani","dob":"28/12/1932","note":"Entrepreneur","lifePath":1,"destiny":1,"psychic":1},
  {"name":"John Von Neumann","dob":"28/12/1903","note":"Mathematician, Math","lifePath":8,"destiny":8,"psychic":1},
  {"name":"Ratan Tata","dob":"28/12/1937","note":"Entrepreneur","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Woodrow Wilson","dob":"28/12/1856","note":"(D), 28th pres (1912-21) (Nobel 1919)","lifePath":6,"destiny":6,"psychic":1},
  {"name":"Jon Voight","dob":"29/12/1938","note":"Actor (Deliverance, Midnight Cowboy)","lifePath":8,"destiny":8,"psychic":2},
  {"name":"Marquise de Pompadour","dob":"29/12/1721","note":"Mistress of French King Louis the 15th","lifePath":7,"destiny":7,"psychic":2},
  {"name":"Pablo Casals","dob":"30/12/1876","note":"Spanish violinist, conductor, composer","lifePath":1,"destiny":1,"psychic":3},
  {"name":"Rudyard Kipling","dob":"30/12/1865","note":"Author who coined White man's burden (Nobel '07)","lifePath":8,"destiny":8,"psychic":3},
  {"name":"Anthony Hopkins","dob":"31/12/1937","note":"Actor","lifePath":9,"destiny":9,"psychic":4},
  {"name":"Henri Matisse","dob":"31/12/1869","note":"French Impressionist painter","lifePath":4,"destiny":4,"psychic":4}
];
